//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACReportGasLog
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public int ACActionId { get; set; }
        public string Description { get; set; }
        public Nullable<int> AmountOfGrams { get; set; }
        public int ACReportGasId { get; set; }
        public Nullable<int> ACReportId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ACAction ACAction { get; set; }
        public virtual ACReport ACReport { get; set; }
        public virtual ACReportGa ACReportGa { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
