//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BisoftProgramUpdate
    {
        public int Id { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ModulePartId { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ModulePart ModulePart { get; set; }
        public virtual Module Module { get; set; }
    }
}
