//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPreSalesModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPreSalesModule()
        {
            this.CarPreSalesModuleDocuments = new HashSet<CarPreSalesModuleDocument>();
        }
    
        public int Id { get; set; }
        public int CarPreSalesId { get; set; }
        public int CarPreSalesModuleOfficeId { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<System.DateTime> PlannedFinished { get; set; }
        public Nullable<int> TimeNr { get; set; }
        public string TimeUnit { get; set; }
        public int OrderNr { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public string PerformedDescription { get; set; }
    
        public virtual CarPreSale CarPreSale { get; set; }
        public virtual CarPreSalesModuleOffice CarPreSalesModuleOffice { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModuleDocument> CarPreSalesModuleDocuments { get; set; }
    }
}
