//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPreSalesModuleOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPreSalesModuleOffice()
        {
            this.CarPreSaleModuleFlowRows = new HashSet<CarPreSaleModuleFlowRow>();
            this.CarPreSalesModules = new HashSet<CarPreSalesModule>();
            this.CarPreSalesModuleOfficeResponsibles = new HashSet<CarPreSalesModuleOfficeResponsible>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
        public Nullable<bool> AddDocument { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> TimeNr { get; set; }
        public string TimeUnit { get; set; }
        public string Description { get; set; }
        public bool IsCarRecieved { get; set; }
        public Nullable<int> CarPreSalesModuleOfficeTypeId { get; set; }
        public Nullable<int> CarPreSalesProtocolId { get; set; }
        public Nullable<bool> ChooseParking { get; set; }
        public Nullable<bool> ChooseKeyCabinet { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> InputMilage { get; set; }
        public Nullable<bool> MarkAsSold { get; set; }
        public Nullable<bool> MarkAsBooked { get; set; }
        public Nullable<bool> OpenPlanning { get; set; }
        public Nullable<bool> ChooseFlow { get; set; }
        public Nullable<bool> ChangeResponsible { get; set; }
        public Nullable<bool> IsSales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSaleModuleFlowRow> CarPreSaleModuleFlowRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModule> CarPreSalesModules { get; set; }
        public virtual CarPreSalesModuleOfficeType CarPreSalesModuleOfficeType { get; set; }
        public virtual CarPreSalesProtocol CarPreSalesProtocol { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModuleOfficeResponsible> CarPreSalesModuleOfficeResponsibles { get; set; }
    }
}
