//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPreSaleFlowGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPreSaleFlowGroup()
        {
            this.CarPreSales = new HashSet<CarPreSale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public int OfficeId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<bool> HasMaintenance { get; set; }
        public string IntervalUnit { get; set; }
        public Nullable<int> IntervalNr { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
        public Nullable<int> CarPreSalesMaintenanceFormId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales { get; set; }
        public virtual CarPreSalesMaintenanceForm CarPreSalesMaintenanceForm { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
    }
}
