//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPreSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPreSale()
        {
            this.CarPreSaleLogs = new HashSet<CarPreSaleLog>();
            this.CarPreSalesModules = new HashSet<CarPreSalesModule>();
        }
    
        public int Id { get; set; }
        public int VehicleCompanyId { get; set; }
        public int OfficeId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> PlannedRecieveDate { get; set; }
        public Nullable<System.DateTime> RecievedDate { get; set; }
        public int CreatedById { get; set; }
        public int ResponsibleId { get; set; }
        public Nullable<int> OfficeParkingId { get; set; }
        public Nullable<System.DateTime> CarTestDate { get; set; }
        public Nullable<int> CarTestPerformedById { get; set; }
        public string CarTestDocPath { get; set; }
        public Nullable<int> OfficeKeyCabinetId { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<int> CarPreSaleFlowGroupId { get; set; }
        public Nullable<int> IntervalNr { get; set; }
        public string IntervalUnit { get; set; }
        public Nullable<System.DateTime> Next { get; set; }
        public Nullable<int> MaintenanceResponsibleId { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<int> InstectionResponsibleId { get; set; }
        public Nullable<int> CarPreSalesMaintenanceFormId { get; set; }
        public Nullable<bool> IsFromBAM { get; set; }
        public Nullable<bool> IsFromHB { get; set; }
    
        public virtual CarPreSaleFlowGroup CarPreSaleFlowGroup { get; set; }
        public virtual CarPreSalesMaintenanceForm CarPreSalesMaintenanceForm { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Employee Employee4 { get; set; }
        public virtual OfficeKeyCabinet OfficeKeyCabinet { get; set; }
        public virtual OfficeParking OfficeParking { get; set; }
        public virtual Office Office { get; set; }
        public virtual VehicleCompany VehicleCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSaleLog> CarPreSaleLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModule> CarPreSalesModules { get; set; }
    }
}
