//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPreSaleModuleFlowRow
    {
        public int Id { get; set; }
        public int CarPreSaleModuleFlowId { get; set; }
        public int CarPreSalesModuleOfficeId { get; set; }
        public int OrderNr { get; set; }
    
        public virtual CarPreSaleModuleFlow CarPreSaleModuleFlow { get; set; }
        public virtual CarPreSalesModuleOffice CarPreSalesModuleOffice { get; set; }
    }
}
