//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPreSalesMaintenanceLager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPreSalesMaintenanceLager()
        {
            this.CarPreSaleLogs = new HashSet<CarPreSaleLog>();
        }
    
        public int Id { get; set; }
        public bool BatteriCheckOK { get; set; }
        public string BatteriCheckInfo { get; set; }
        public bool BrakeCheckOK { get; set; }
        public string BrakeCheckInfo { get; set; }
        public bool TireCheckOK { get; set; }
        public string TireCheckInfo { get; set; }
        public bool HighVoltCheckOK { get; set; }
        public string HighVoltCheckInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSaleLog> CarPreSaleLogs { get; set; }
    }
}
