//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Offices = new HashSet<Office>();
            this.CompanyCleanSettings = new HashSet<CompanyCleanSetting>();
            this.CompanyEmployeeGroups = new HashSet<CompanyEmployeeGroup>();
            this.CompanyImages = new HashSet<CompanyImage>();
            this.CompanyRegions = new HashSet<CompanyRegion>();
            this.CompanyVehicleBrands = new HashSet<CompanyVehicleBrand>();
            this.CRAnalysisHeaders = new HashSet<CRAnalysisHeader>();
            this.CRFinalDecisionHeaders = new HashSet<CRFinalDecisionHeader>();
            this.CRFollowUpHeaders = new HashSet<CRFollowUpHeader>();
            this.CRHeaders = new HashSet<CRHeader>();
            this.CustomerCompanies = new HashSet<CustomerCompany>();
            this.EmployeePositionCompanies = new HashSet<EmployeePositionCompany>();
            this.ERAnalysisHeaders = new HashSet<ERAnalysisHeader>();
            this.ERFinalDecisionHeaders = new HashSet<ERFinalDecisionHeader>();
            this.ERHeaders = new HashSet<ERHeader>();
            this.ICErrorCodeMainGroups = new HashSet<ICErrorCodeMainGroup>();
            this.IncidentReportFinalDecisions = new HashSet<IncidentReportFinalDecision>();
            this.IncidentReportIncidents = new HashSet<IncidentReportIncident>();
            this.IncidentReportInjuryTypes = new HashSet<IncidentReportInjuryType>();
            this.IncidentReportTypes = new HashSet<IncidentReportType>();
            this.InternalControlTemplates = new HashSet<InternalControlTemplate>();
            this.InternalControlTemplateGroups = new HashSet<InternalControlTemplateGroup>();
            this.Manuals = new HashSet<Manual>();
            this.ManualDocumentPDFCompanies = new HashSet<ManualDocumentPDFCompany>();
            this.ManualDocumentTemplateCompanies = new HashSet<ManualDocumentTemplateCompany>();
            this.ManualTemplateResponsibles = new HashSet<ManualTemplateResponsible>();
            this.ModuleCompanies = new HashSet<ModuleCompany>();
            this.ModulePartCompanies = new HashSet<ModulePartCompany>();
            this.PropertyProducts = new HashSet<PropertyProduct>();
            this.QRAnalysisHeaders = new HashSet<QRAnalysisHeader>();
            this.QRFinalDecisionHeaders = new HashSet<QRFinalDecisionHeader>();
            this.QRHeaders = new HashSet<QRHeader>();
            this.RiskAnalysisCompanies = new HashSet<RiskAnalysisCompany>();
            this.RiskAnalysisEffects = new HashSet<RiskAnalysisEffect>();
            this.RiskAnalysisGroups = new HashSet<RiskAnalysisGroup>();
            this.RiskAnalysisProbabilities = new HashSet<RiskAnalysisProbability>();
            this.RiskAnalysisSubGroups = new HashSet<RiskAnalysisSubGroup>();
            this.ToolCalibrationTypes = new HashSet<ToolCalibrationType>();
            this.ToolCalibrators = new HashSet<ToolCalibrator>();
            this.ToolMaintenanceRutineCompanies = new HashSet<ToolMaintenanceRutineCompany>();
            this.ToolMaintenanceTypes = new HashSet<ToolMaintenanceType>();
            this.ToolManufacturers = new HashSet<ToolManufacturer>();
            this.ToolProducts = new HashSet<ToolProduct>();
            this.ToolWebLinkCompanies = new HashSet<ToolWebLinkCompany>();
            this.ToolVWPricesCompanies = new HashSet<ToolVWPricesCompany>();
            this.VehicleCompanies = new HashSet<VehicleCompany>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public bool Status { get; set; }
        public string Ucid { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> HasCalibrationSignature { get; set; }
        public Nullable<bool> ShowOnlyMyOffice { get; set; }
        public Nullable<bool> HideToolPrices { get; set; }
        public string NameOfOffice { get; set; }
        public string NameOfOffices { get; set; }
        public string NameOfToolName { get; set; }
        public string NameOfToolNr { get; set; }
        public Nullable<bool> OnlyCompToolRutines { get; set; }
        public string NameOfTool { get; set; }
        public string NameOfNewTool { get; set; }
        public string NameOfToolGroup { get; set; }
        public Nullable<bool> HideCerificateNr { get; set; }
        public Nullable<bool> UseToolCalibrationType { get; set; }
        public Nullable<bool> UseToolMaintenanceType { get; set; }
        public Nullable<bool> UseToolAdjustment { get; set; }
        public Nullable<bool> LockToolWebLink { get; set; }
        public Nullable<bool> LockToolGroups { get; set; }
        public Nullable<bool> UseOutOfOrder { get; set; }
        public Nullable<bool> IsSortToolProduct { get; set; }
        public Nullable<bool> UseToolSerieNr { get; set; }
        public Nullable<bool> LockToolCalibrationForm { get; set; }
        public string ToolChangeOfficeEmail { get; set; }
        public string ToolDeleteEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Office> Offices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyCleanSetting> CompanyCleanSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyEmployeeGroup> CompanyEmployeeGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyImage> CompanyImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyRegion> CompanyRegions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyVehicleBrand> CompanyVehicleBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRAnalysisHeader> CRAnalysisHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRFinalDecisionHeader> CRFinalDecisionHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRFollowUpHeader> CRFollowUpHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRHeader> CRHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCompany> CustomerCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePositionCompany> EmployeePositionCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERAnalysisHeader> ERAnalysisHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERFinalDecisionHeader> ERFinalDecisionHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERHeader> ERHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICErrorCodeMainGroup> ICErrorCodeMainGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportFinalDecision> IncidentReportFinalDecisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportIncident> IncidentReportIncidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportInjuryType> IncidentReportInjuryTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportType> IncidentReportTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlTemplate> InternalControlTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlTemplateGroup> InternalControlTemplateGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manual> Manuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualDocumentPDFCompany> ManualDocumentPDFCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualDocumentTemplateCompany> ManualDocumentTemplateCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualTemplateResponsible> ManualTemplateResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleCompany> ModuleCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePartCompany> ModulePartCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyProduct> PropertyProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRAnalysisHeader> QRAnalysisHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRFinalDecisionHeader> QRFinalDecisionHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRHeader> QRHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisCompany> RiskAnalysisCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisEffect> RiskAnalysisEffects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisGroup> RiskAnalysisGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisProbability> RiskAnalysisProbabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisSubGroup> RiskAnalysisSubGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationType> ToolCalibrationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrator> ToolCalibrators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceRutineCompany> ToolMaintenanceRutineCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceType> ToolMaintenanceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolManufacturer> ToolManufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolProduct> ToolProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolWebLinkCompany> ToolWebLinkCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolVWPricesCompany> ToolVWPricesCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleCompany> VehicleCompanies { get; set; }
    }
}
