//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEmployeeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyEmployeeGroup()
        {
            this.CompanyEmployeeGroupRows = new HashSet<CompanyEmployeeGroupRow>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CompanyId { get; set; }
        public Nullable<bool> SeeRegion { get; set; }
        public Nullable<bool> SeeAll { get; set; }
        public Nullable<bool> SeeOfficeToolVarningsStart { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyEmployeeGroupRow> CompanyEmployeeGroupRows { get; set; }
    }
}
