//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRLog
    {
        public int Id { get; set; }
        public int CustomerReportId { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public bool Deleted { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int LogTypeId { get; set; }
        public string Subject { get; set; }
    
        public virtual CustomerReport CustomerReport { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual CRLogType CRLogType { get; set; }
    }
}
