//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMeasureReport
    {
        public int Id { get; set; }
        public int CustomerReportId { get; set; }
        public int ControlStatusId { get; set; }
        public string FinishUnit { get; set; }
        public Nullable<int> FinishNr { get; set; }
        public bool IsBeforeControlStatus { get; set; }
        public bool Activated { get; set; }
        public bool IsLogMeasure { get; set; }
        public bool IsModule { get; set; }
        public bool IsStatus { get; set; }
        public Nullable<int> CRModuleId { get; set; }
        public Nullable<int> CRStatusId { get; set; }
        public Nullable<int> CRLogMeasureId { get; set; }
        public Nullable<System.DateTime> FinishBefore { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<bool> FinishReport { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
    
        public virtual CRLogMeasureReport CRLogMeasureReport { get; set; }
        public virtual CRStatu CRStatu { get; set; }
        public virtual CRStatu CRStatu1 { get; set; }
        public virtual CustomerReport CustomerReport { get; set; }
        public virtual CRModule CRModule { get; set; }
    }
}
