//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRModuleEmailNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRModuleEmailNotification()
        {
            this.CRModuleEmailNotificationReceivers = new HashSet<CRModuleEmailNotificationReceiver>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int ModuleId { get; set; }
        public int Weeks { get; set; }
        public int Days { get; set; }
        public int Hours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRModuleEmailNotificationReceiver> CRModuleEmailNotificationReceivers { get; set; }
        public virtual CRModule CRModule { get; set; }
        public virtual Office Office { get; set; }
    }
}
