//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRPositiveGroupQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRPositiveGroupQuestion()
        {
            this.CustomerPositiveReportRows = new HashSet<CustomerPositiveReportRow>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CRPositiveGroupId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CRPositiveGroup CRPositiveGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPositiveReportRow> CustomerPositiveReportRows { get; set; }
    }
}
