//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRPositiveGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRPositiveGroup()
        {
            this.CRPositiveGroupQuestions = new HashSet<CRPositiveGroupQuestion>();
            this.CustomerReportPositives = new HashSet<CustomerReportPositive>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OfficeId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRPositiveGroupQuestion> CRPositiveGroupQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportPositive> CustomerReportPositives { get; set; }
    }
}
