//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerReport()
        {
            this.CQReportTaskRows = new HashSet<CQReportTaskRow>();
            this.CRAttatchedFiles = new HashSet<CRAttatchedFile>();
            this.CRLogs = new HashSet<CRLog>();
            this.CRMeasureReports = new HashSet<CRMeasureReport>();
            this.QualityReports = new HashSet<QualityReport>();
        }
    
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public string Description { get; set; }
        public int ReportNr { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public int VehicleId { get; set; }
        public int CustomerId { get; set; }
        public string Status { get; set; }
        public int Responsible { get; set; }
        public Nullable<int> CausedBy { get; set; }
        public int Year { get; set; }
        public Nullable<int> AnalysisHeaderId { get; set; }
        public string AnalysisText { get; set; }
        public int OfficeId { get; set; }
        public int StatusId { get; set; }
        public decimal TotalCost { get; set; }
        public string FinalDecisionText { get; set; }
        public Nullable<int> FinalDecisionHeaderId { get; set; }
        public Nullable<decimal> FinalDecisionCost { get; set; }
        public Nullable<int> FollowUpHeaderId { get; set; }
        public string FollowUpText { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> AnalysisCausedBy { get; set; }
        public Nullable<int> AnalysisFaultId { get; set; }
        public Nullable<int> CustomerReportPositiveId { get; set; }
        public Nullable<bool> IsHotAlert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQReportTaskRow> CQReportTaskRows { get; set; }
        public virtual CRAnalysisFault CRAnalysisFault { get; set; }
        public virtual CRAnalysisHeader CRAnalysisHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRAttatchedFile> CRAttatchedFiles { get; set; }
        public virtual CRFinalDecisionHeader CRFinalDecisionHeader { get; set; }
        public virtual CRFollowUpHeader CRFollowUpHeader { get; set; }
        public virtual CRHeader CRHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRLog> CRLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMeasureReport> CRMeasureReports { get; set; }
        public virtual CRResponsible CRResponsible { get; set; }
        public virtual CRStatu CRStatu { get; set; }
        public virtual CustomerCompany CustomerCompany { get; set; }
        public virtual CustomerReportPositive CustomerReportPositive { get; set; }
        public virtual OfficeDepartment OfficeDepartment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        public virtual VehicleCompany VehicleCompany { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityReport> QualityReports { get; set; }
    }
}
