//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPositiveGrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerPositiveGrade()
        {
            this.CustomerPositiveReportRows = new HashSet<CustomerPositiveReportRow>();
            this.CustomerReportPositives = new HashSet<CustomerReportPositive>();
        }
    
        public int Id { get; set; }
        public string GradeName { get; set; }
        public Nullable<decimal> GradeValue { get; set; }
        public string GradeIcon { get; set; }
        public int OfficeId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<bool> CreateCRReport { get; set; }
    
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPositiveReportRow> CustomerPositiveReportRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportPositive> CustomerReportPositives { get; set; }
    }
}
