//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReportPositive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerReportPositive()
        {
            this.CRPositiveDepartmentTasks = new HashSet<CRPositiveDepartmentTask>();
            this.CustomerPositiveReportRows = new HashSet<CustomerPositiveReportRow>();
            this.CustomerReports = new HashSet<CustomerReport>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int ReportNr { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public int VehicleId { get; set; }
        public int CustomerId { get; set; }
        public int Year { get; set; }
        public int OfficeId { get; set; }
        public int StatusId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> CustomerPositiveGradeId { get; set; }
        public Nullable<int> OfficeDepartmentTaskGroupId { get; set; }
        public int CRPositiveGroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRPositiveDepartmentTask> CRPositiveDepartmentTasks { get; set; }
        public virtual CRPositiveGroup CRPositiveGroup { get; set; }
        public virtual CRStatu CRStatu { get; set; }
        public virtual CustomerCompany CustomerCompany { get; set; }
        public virtual CustomerPositiveGrade CustomerPositiveGrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPositiveReportRow> CustomerPositiveReportRows { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual OfficeDepartmentTaskGroup OfficeDepartmentTaskGroup { get; set; }
        public virtual Office Office { get; set; }
        public virtual VehicleCompany VehicleCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReport> CustomerReports { get; set; }
    }
}
