//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPositiveReportRow
    {
        public int Id { get; set; }
        public int CustomerReportPositiveId { get; set; }
        public int CRReportGroupQuestionId { get; set; }
        public int CustomerPostitveGradeId { get; set; }
        public Nullable<decimal> GradeValue { get; set; }
    
        public virtual CRPositiveGroupQuestion CRPositiveGroupQuestion { get; set; }
        public virtual CustomerPositiveGrade CustomerPositiveGrade { get; set; }
        public virtual CustomerReportPositive CustomerReportPositive { get; set; }
    }
}
