//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSettingsOffice
    {
        public int Id { get; set; }
        public string Server { get; set; }
        public string Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> UseSSL { get; set; }
        public int OfficeId { get; set; }
        public string ReplyTo { get; set; }
        public bool AllowNotify { get; set; }
    
        public virtual Office Office { get; set; }
    }
}
