//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ACReports = new HashSet<ACReport>();
            this.ACReportGasLogs = new HashSet<ACReportGasLog>();
            this.BisoftProgramUpdates = new HashSet<BisoftProgramUpdate>();
            this.CarPreSales = new HashSet<CarPreSale>();
            this.CarPreSales1 = new HashSet<CarPreSale>();
            this.CarPreSales2 = new HashSet<CarPreSale>();
            this.CarPreSales3 = new HashSet<CarPreSale>();
            this.CarPreSales4 = new HashSet<CarPreSale>();
            this.CarPreSaleFlowGroups = new HashSet<CarPreSaleFlowGroup>();
            this.CarPreSaleLogs = new HashSet<CarPreSaleLog>();
            this.CarPreSalesModules = new HashSet<CarPreSalesModule>();
            this.CarPreSalesModuleOffices = new HashSet<CarPreSalesModuleOffice>();
            this.CarPreSalesModuleOfficeResponsibles = new HashSet<CarPreSalesModuleOfficeResponsible>();
            this.CompanyEmployeeGroupRows = new HashSet<CompanyEmployeeGroupRow>();
            this.CompanyRegions = new HashSet<CompanyRegion>();
            this.CRLogs = new HashSet<CRLog>();
            this.CRModuleEmailNotificationReceivers = new HashSet<CRModuleEmailNotificationReceiver>();
            this.CRResponsibles = new HashSet<CRResponsible>();
            this.CRStatusEmailNotifications = new HashSet<CRStatusEmailNotification>();
            this.CustomerReportImprovments = new HashSet<CustomerReportImprovment>();
            this.CustomerReportPositives = new HashSet<CustomerReportPositive>();
            this.CustomerReports = new HashSet<CustomerReport>();
            this.CustomerReports1 = new HashSet<CustomerReport>();
            this.EmailSents = new HashSet<EmailSent>();
            this.EmployeeAssSkillsErSettings = new HashSet<EmployeeAssSkillsErSetting>();
            this.EmployeeAssSkillsIBSettings = new HashSet<EmployeeAssSkillsIBSetting>();
            this.EmployeeAssSkillsIRSettings = new HashSet<EmployeeAssSkillsIRSetting>();
            this.EmployeeAssSkillsKASettings = new HashSet<EmployeeAssSkillsKASetting>();
            this.EmployeeAssSkillsKKSettings = new HashSet<EmployeeAssSkillsKKSetting>();
            this.EmployeeAssSkillsTASettings = new HashSet<EmployeeAssSkillsTASetting>();
            this.EmployeeAssSkillsUASettings = new HashSet<EmployeeAssSkillsUASetting>();
            this.EmployeeEducations = new HashSet<EmployeeEducation>();
            this.EmployeeGroupRows = new HashSet<EmployeeGroupRow>();
            this.EmployeeManualPartDocs = new HashSet<EmployeeManualPartDoc>();
            this.EmployeePositions = new HashSet<EmployeePosition>();
            this.EmployeeWorkExperiences = new HashSet<EmployeeWorkExperience>();
            this.EnviromentalReports = new HashSet<EnviromentalReport>();
            this.EnviromentalReports1 = new HashSet<EnviromentalReport>();
            this.ERActionPlans = new HashSet<ERActionPlan>();
            this.ERImprovmentResponsibles = new HashSet<ERImprovmentResponsible>();
            this.ERImprovments = new HashSet<ERImprovment>();
            this.ERLogs = new HashSet<ERLog>();
            this.ERResponsibles = new HashSet<ERResponsible>();
            this.ERStatusEmailNotifications = new HashSet<ERStatusEmailNotification>();
            this.FollowUps = new HashSet<FollowUp>();
            this.FollowUpEmployeePermissions = new HashSet<FollowUpEmployeePermission>();
            this.FollowUpRows = new HashSet<FollowUpRow>();
            this.IncidentReports = new HashSet<IncidentReport>();
            this.IncidentReports1 = new HashSet<IncidentReport>();
            this.IncidentReports2 = new HashSet<IncidentReport>();
            this.IncidentReportLogs = new HashSet<IncidentReportLog>();
            this.IncidentReportVictums = new HashSet<IncidentReportVictum>();
            this.InternalControlOffices = new HashSet<InternalControlOffice>();
            this.InternalControlOfficeLogs = new HashSet<InternalControlOfficeLog>();
            this.InternalControlOfficeLogs1 = new HashSet<InternalControlOfficeLog>();
            this.Manuals = new HashSet<Manual>();
            this.ManualAdminOfficeConnections = new HashSet<ManualAdminOfficeConnection>();
            this.ManualDocumentPDFCompanies = new HashSet<ManualDocumentPDFCompany>();
            this.ManualDocumentTemplateCompanies = new HashSet<ManualDocumentTemplateCompany>();
            this.ManualParts = new HashSet<ManualPart>();
            this.ManualPartDocuments = new HashSet<ManualPartDocument>();
            this.ManualPartDocumentEmployees = new HashSet<ManualPartDocumentEmployee>();
            this.ManualPartDocumentLogs = new HashSet<ManualPartDocumentLog>();
            this.ManualPartDocumentLogs1 = new HashSet<ManualPartDocumentLog>();
            this.ManualPartDocumentLogEmployees = new HashSet<ManualPartDocumentLogEmployee>();
            this.ManualPartDocumentPlans = new HashSet<ManualPartDocumentPlan>();
            this.ManualPartDocumentPlanEmployees = new HashSet<ManualPartDocumentPlanEmployee>();
            this.ManualPartSuggestions = new HashSet<ManualPartSuggestion>();
            this.ManualPartSuggestions1 = new HashSet<ManualPartSuggestion>();
            this.ManualPartTemplates = new HashSet<ManualPartTemplate>();
            this.ManualPartVersions = new HashSet<ManualPartVersion>();
            this.ManualSuggestions = new HashSet<ManualSuggestion>();
            this.ManualSuggestions1 = new HashSet<ManualSuggestion>();
            this.ManualTemplates = new HashSet<ManualTemplate>();
            this.ManualTemplateResponsibles = new HashSet<ManualTemplateResponsible>();
            this.ModuleEmployees = new HashSet<ModuleEmployee>();
            this.ModulePartEmployees = new HashSet<ModulePartEmployee>();
            this.OfficeDepartments = new HashSet<OfficeDepartment>();
            this.OfficeDepartments1 = new HashSet<OfficeDepartment>();
            this.OfficeDepartmentTasks = new HashSet<OfficeDepartmentTask>();
            this.OfficeDepartmentTaskGroups = new HashSet<OfficeDepartmentTaskGroup>();
            this.OfficeDepartmentTaskGroupVersions = new HashSet<OfficeDepartmentTaskGroupVersion>();
            this.OfficeDepartmentTaskVersions = new HashSet<OfficeDepartmentTaskVersion>();
            this.OfficeDepartmentVersions = new HashSet<OfficeDepartmentVersion>();
            this.Offices = new HashSet<Office>();
            this.OfficeSafetyEmployees = new HashSet<OfficeSafetyEmployee>();
            this.OfficeVehicleBrandResponsibles = new HashSet<OfficeVehicleBrandResponsible>();
            this.Properties = new HashSet<Property>();
            this.Properties1 = new HashSet<Property>();
            this.Properties2 = new HashSet<Property>();
            this.Properties3 = new HashSet<Property>();
            this.PropertyControlLogs = new HashSet<PropertyControlLog>();
            this.PropertyInspectionLogs = new HashSet<PropertyInspectionLog>();
            this.PropertyInspectionLogs1 = new HashSet<PropertyInspectionLog>();
            this.PropertyLogs = new HashSet<PropertyLog>();
            this.PropertyMaintenanceLogs = new HashSet<PropertyMaintenanceLog>();
            this.QRActionPlans = new HashSet<QRActionPlan>();
            this.QRCausedBies = new HashSet<QRCausedBy>();
            this.QRImprovmentResponsibles = new HashSet<QRImprovmentResponsible>();
            this.QRImprovments = new HashSet<QRImprovment>();
            this.QRImprovments1 = new HashSet<QRImprovment>();
            this.QRImprovments2 = new HashSet<QRImprovment>();
            this.QRImprovments3 = new HashSet<QRImprovment>();
            this.QRLogs = new HashSet<QRLog>();
            this.QRModuleEmailNotificationReceivers = new HashSet<QRModuleEmailNotificationReceiver>();
            this.QRResponsibles = new HashSet<QRResponsible>();
            this.QRStatusEmailNotifications = new HashSet<QRStatusEmailNotification>();
            this.QualityReports = new HashSet<QualityReport>();
            this.QualityReports1 = new HashSet<QualityReport>();
            this.RiskAnalysisOffices = new HashSet<RiskAnalysisOffice>();
            this.RiskAnalysisOfficeLogs = new HashSet<RiskAnalysisOfficeLog>();
            this.Supports = new HashSet<Support>();
            this.SwedAssessmentSkillsERs = new HashSet<SwedAssessmentSkillsER>();
            this.SwedAssessmentSkillsERs1 = new HashSet<SwedAssessmentSkillsER>();
            this.SwedAssessmentSkillsIBs = new HashSet<SwedAssessmentSkillsIB>();
            this.SwedAssessmentSkillsIBs1 = new HashSet<SwedAssessmentSkillsIB>();
            this.SwedAssessmentSkillsIRs = new HashSet<SwedAssessmentSkillsIR>();
            this.SwedAssessmentSkillsIRs1 = new HashSet<SwedAssessmentSkillsIR>();
            this.SwedAssessmentSkillsKAs = new HashSet<SwedAssessmentSkillsKA>();
            this.SwedAssessmentSkillsKAs1 = new HashSet<SwedAssessmentSkillsKA>();
            this.SwedAssessmentSkillsKKs = new HashSet<SwedAssessmentSkillsKK>();
            this.SwedAssessmentSkillsKKs1 = new HashSet<SwedAssessmentSkillsKK>();
            this.SwedAssessmentSkillsTAs = new HashSet<SwedAssessmentSkillsTA>();
            this.SwedAssessmentSkillsTAs1 = new HashSet<SwedAssessmentSkillsTA>();
            this.SwedAssessmentSkillsUAs = new HashSet<SwedAssessmentSkillsUA>();
            this.SwedAssessmentSkillsUAs1 = new HashSet<SwedAssessmentSkillsUA>();
            this.SwedDocumentReviews = new HashSet<SwedDocumentReview>();
            this.SwedERSamplingCars = new HashSet<SwedERSamplingCar>();
            this.SwedJointInfoEducations = new HashSet<SwedJointInfoEducation>();
            this.SwedJointInfoEducations1 = new HashSet<SwedJointInfoEducation>();
            this.SwedJointInfoEducationParticipants = new HashSet<SwedJointInfoEducationParticipant>();
            this.SwedManagementReview381 = new HashSet<SwedManagementReview381>();
            this.SwedManagementReview381Employees = new HashSet<SwedManagementReview381Employees>();
            this.SwedOfficeAreaEmployees = new HashSet<SwedOfficeAreaEmployee>();
            this.SwedPowerOfAttorneyERs = new HashSet<SwedPowerOfAttorneyER>();
            this.SwedPowerOfAttorneyERs1 = new HashSet<SwedPowerOfAttorneyER>();
            this.Tools = new HashSet<Tool>();
            this.Tools1 = new HashSet<Tool>();
            this.Tools2 = new HashSet<Tool>();
            this.Tools3 = new HashSet<Tool>();
            this.ToolBorroweds = new HashSet<ToolBorrowed>();
            this.ToolCalibration20MeterDistance = new HashSet<ToolCalibration20MeterDistance>();
            this.ToolCalibrationACWaecoes = new HashSet<ToolCalibrationACWaeco>();
            this.ToolCalibrationBreaktesterOptimoes = new HashSet<ToolCalibrationBreaktesterOptimo>();
            this.ToolCalibrationCircumferences = new HashSet<ToolCalibrationCircumference>();
            this.ToolCalibrationDocumentReports = new HashSet<ToolCalibrationDocumentReport>();
            this.ToolCalibrationDocumentReports1 = new HashSet<ToolCalibrationDocumentReport>();
            this.ToolCalibrationDocumentReportVersions = new HashSet<ToolCalibrationDocumentReportVersion>();
            this.ToolCalibrationDocumentReportVersions1 = new HashSet<ToolCalibrationDocumentReportVersion>();
            this.ToolCalibrationFourGasMeterHexanProes = new HashSet<ToolCalibrationFourGasMeterHexanPro>();
            this.ToolCalibrationFourGasMeterPropanProes = new HashSet<ToolCalibrationFourGasMeterPropanPro>();
            this.ToolCalibrationLeakFinders = new HashSet<ToolCalibrationLeakFinder>();
            this.ToolCalibrationLightControlProes = new HashSet<ToolCalibrationLightControlPro>();
            this.ToolCalibrationLogs = new HashSet<ToolCalibrationLog>();
            this.ToolCalibrationLogs1 = new HashSet<ToolCalibrationLog>();
            this.ToolCalibrationLogs2 = new HashSet<ToolCalibrationLog>();
            this.ToolCalibrationPressureTesters = new HashSet<ToolCalibrationPressureTester>();
            this.ToolGroupInventories = new HashSet<ToolGroupInventory>();
            this.ToolGroupInventoryLogRows = new HashSet<ToolGroupInventoryLogRow>();
            this.ToolLogs = new HashSet<ToolLog>();
            this.ToolMaintenanceLogs = new HashSet<ToolMaintenanceLog>();
            this.ToolMaintenanceRutines = new HashSet<ToolMaintenanceRutine>();
            this.ToolMaintenanceRutineCompanies = new HashSet<ToolMaintenanceRutineCompany>();
            this.ToolMaintenanceRutineOffices = new HashSet<ToolMaintenanceRutineOffice>();
        }
    
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Birthdate { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public bool Status { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int OfficeId { get; set; }
        public string EmployeeNr { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string MobilePhone { get; set; }
        public bool CompanyAdmin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Picture { get; set; }
        public Nullable<int> EmployeePositionCompanyId { get; set; }
        public string StartPageSettings { get; set; }
        public string CertNr { get; set; }
        public Nullable<bool> HasOutlookCalender { get; set; }
        public Nullable<bool> CanRegretFinalAproval { get; set; }
        public string SalesNr { get; set; }
        public string ClosestRelative { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACReport> ACReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACReportGasLog> ACReportGasLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BisoftProgramUpdate> BisoftProgramUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSaleFlowGroup> CarPreSaleFlowGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSaleLog> CarPreSaleLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModule> CarPreSalesModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModuleOffice> CarPreSalesModuleOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModuleOfficeResponsible> CarPreSalesModuleOfficeResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyEmployeeGroupRow> CompanyEmployeeGroupRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyRegion> CompanyRegions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRLog> CRLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRModuleEmailNotificationReceiver> CRModuleEmailNotificationReceivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRResponsible> CRResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRStatusEmailNotification> CRStatusEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportImprovment> CustomerReportImprovments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportPositive> CustomerReportPositives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReport> CustomerReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReport> CustomerReports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSent> EmailSents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssSkillsErSetting> EmployeeAssSkillsErSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssSkillsIBSetting> EmployeeAssSkillsIBSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssSkillsIRSetting> EmployeeAssSkillsIRSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssSkillsKASetting> EmployeeAssSkillsKASettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssSkillsKKSetting> EmployeeAssSkillsKKSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssSkillsTASetting> EmployeeAssSkillsTASettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssSkillsUASetting> EmployeeAssSkillsUASettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeEducation> EmployeeEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGroupRow> EmployeeGroupRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeManualPartDoc> EmployeeManualPartDocs { get; set; }
        public virtual EmployeePositionCompany EmployeePositionCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePosition> EmployeePositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeWorkExperience> EmployeeWorkExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnviromentalReport> EnviromentalReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnviromentalReport> EnviromentalReports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERActionPlan> ERActionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERImprovmentResponsible> ERImprovmentResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERImprovment> ERImprovments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERLog> ERLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERResponsible> ERResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERStatusEmailNotification> ERStatusEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUp> FollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpEmployeePermission> FollowUpEmployeePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpRow> FollowUpRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReport> IncidentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReport> IncidentReports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReport> IncidentReports2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportLog> IncidentReportLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportVictum> IncidentReportVictums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOffice> InternalControlOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLog> InternalControlOfficeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLog> InternalControlOfficeLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manual> Manuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualAdminOfficeConnection> ManualAdminOfficeConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualDocumentPDFCompany> ManualDocumentPDFCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualDocumentTemplateCompany> ManualDocumentTemplateCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPart> ManualParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocument> ManualPartDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentEmployee> ManualPartDocumentEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLog> ManualPartDocumentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLog> ManualPartDocumentLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogEmployee> ManualPartDocumentLogEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentPlan> ManualPartDocumentPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentPlanEmployee> ManualPartDocumentPlanEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartSuggestion> ManualPartSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartSuggestion> ManualPartSuggestions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartTemplate> ManualPartTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartVersion> ManualPartVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualSuggestion> ManualSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualSuggestion> ManualSuggestions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualTemplate> ManualTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualTemplateResponsible> ManualTemplateResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleEmployee> ModuleEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePartEmployee> ModulePartEmployees { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartment> OfficeDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartment> OfficeDepartments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTask> OfficeDepartmentTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskGroup> OfficeDepartmentTaskGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskGroupVersion> OfficeDepartmentTaskGroupVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskVersion> OfficeDepartmentTaskVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentVersion> OfficeDepartmentVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Office> Offices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeSafetyEmployee> OfficeSafetyEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeVehicleBrandResponsible> OfficeVehicleBrandResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyControlLog> PropertyControlLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyInspectionLog> PropertyInspectionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyInspectionLog> PropertyInspectionLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyLog> PropertyLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyMaintenanceLog> PropertyMaintenanceLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRActionPlan> QRActionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCausedBy> QRCausedBies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovmentResponsible> QRImprovmentResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovment> QRImprovments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovment> QRImprovments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovment> QRImprovments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovment> QRImprovments3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRLog> QRLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRModuleEmailNotificationReceiver> QRModuleEmailNotificationReceivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRResponsible> QRResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRStatusEmailNotification> QRStatusEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityReport> QualityReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityReport> QualityReports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOffice> RiskAnalysisOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOfficeLog> RiskAnalysisOfficeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Support> Supports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsER> SwedAssessmentSkillsERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsER> SwedAssessmentSkillsERs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsIB> SwedAssessmentSkillsIBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsIB> SwedAssessmentSkillsIBs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsIR> SwedAssessmentSkillsIRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsIR> SwedAssessmentSkillsIRs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsKA> SwedAssessmentSkillsKAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsKA> SwedAssessmentSkillsKAs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsKK> SwedAssessmentSkillsKKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsKK> SwedAssessmentSkillsKKs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsTA> SwedAssessmentSkillsTAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsTA> SwedAssessmentSkillsTAs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsUA> SwedAssessmentSkillsUAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsUA> SwedAssessmentSkillsUAs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedDocumentReview> SwedDocumentReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedERSamplingCar> SwedERSamplingCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedJointInfoEducation> SwedJointInfoEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedJointInfoEducation> SwedJointInfoEducations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedJointInfoEducationParticipant> SwedJointInfoEducationParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedManagementReview381> SwedManagementReview381 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedManagementReview381Employees> SwedManagementReview381Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedOfficeAreaEmployee> SwedOfficeAreaEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedPowerOfAttorneyER> SwedPowerOfAttorneyERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedPowerOfAttorneyER> SwedPowerOfAttorneyERs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolBorrowed> ToolBorroweds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibration20MeterDistance> ToolCalibration20MeterDistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationACWaeco> ToolCalibrationACWaecoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationBreaktesterOptimo> ToolCalibrationBreaktesterOptimoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationCircumference> ToolCalibrationCircumferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationDocumentReport> ToolCalibrationDocumentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationDocumentReport> ToolCalibrationDocumentReports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationDocumentReportVersion> ToolCalibrationDocumentReportVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationDocumentReportVersion> ToolCalibrationDocumentReportVersions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationFourGasMeterHexanPro> ToolCalibrationFourGasMeterHexanProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationFourGasMeterPropanPro> ToolCalibrationFourGasMeterPropanProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLeakFinder> ToolCalibrationLeakFinders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLightControlPro> ToolCalibrationLightControlProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationPressureTester> ToolCalibrationPressureTesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolGroupInventory> ToolGroupInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolGroupInventoryLogRow> ToolGroupInventoryLogRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolLog> ToolLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceLog> ToolMaintenanceLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceRutine> ToolMaintenanceRutines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceRutineCompany> ToolMaintenanceRutineCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceRutineOffice> ToolMaintenanceRutineOffices { get; set; }
    }
}
