//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnviromentalReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnviromentalReport()
        {
            this.ERLogs = new HashSet<ERLog>();
            this.ERReportMeasures = new HashSet<ERReportMeasure>();
        }
    
        public int Id { get; set; }
        public int ERHeaderId { get; set; }
        public string Description { get; set; }
        public int ReportNr { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string Status { get; set; }
        public int ERResponsibleId { get; set; }
        public int OfficeDepartmentId { get; set; }
        public int Year { get; set; }
        public Nullable<int> ERAnalysisHeaderId { get; set; }
        public string AnalysisText { get; set; }
        public int OfficeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string FinalDecisionText { get; set; }
        public Nullable<int> ERFinalDecisionHeaderId { get; set; }
        public Nullable<decimal> FinalDecisionCost { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> AnalysisCausedById { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ERAnalysisHeader ERAnalysisHeader { get; set; }
        public virtual ERFinalDecisionHeader ERFinalDecisionHeader { get; set; }
        public virtual ERHeader ERHeader { get; set; }
        public virtual ERResponsible ERResponsible { get; set; }
        public virtual ERStatu ERStatu { get; set; }
        public virtual OfficeDepartment OfficeDepartment { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERLog> ERLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERReportMeasure> ERReportMeasures { get; set; }
    }
}
