//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERActionPlanERHeader
    {
        public int Id { get; set; }
        public int ERHeaderId { get; set; }
        public int ERActionPlanId { get; set; }
    
        public virtual ERActionPlan ERActionPlan { get; set; }
        public virtual ERHeader ERHeader { get; set; }
    }
}
