//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERActionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERActionPlan()
        {
            this.ERActionPlanERAnalysisHeaders = new HashSet<ERActionPlanERAnalysisHeader>();
            this.ERActionPlanERHeaders = new HashSet<ERActionPlanERHeader>();
            this.ERImprovments = new HashSet<ERImprovment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Purpose { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public int OfficeId { get; set; }
        public Nullable<System.DateTime> CompareStart { get; set; }
        public Nullable<System.DateTime> CompareEnd { get; set; }
        public Nullable<int> ImpromentMoneyPercent { get; set; }
        public Nullable<int> ImprovmentNrPercent { get; set; }
        public System.DateTime ImplementStart { get; set; }
        public System.DateTime ImplementEnd { get; set; }
        public int ImprovmentResponsibleId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ERImprovmentResponsible ERImprovmentResponsible { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERActionPlanERAnalysisHeader> ERActionPlanERAnalysisHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERActionPlanERHeader> ERActionPlanERHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERImprovment> ERImprovments { get; set; }
    }
}
