//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERImprovment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERImprovment()
        {
            this.ERImprovmentERAnalysisHeaders = new HashSet<ERImprovmentERAnalysisHeader>();
            this.ERImprovmentERHeaders = new HashSet<ERImprovmentERHeader>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int OfficeId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public int ResponsibleId { get; set; }
        public Nullable<int> ERActionPlanId { get; set; }
        public Nullable<int> GoalInMoneyPercent { get; set; }
        public Nullable<int> GoalInNrPercent { get; set; }
        public Nullable<System.DateTime> ComparePeriodStart { get; set; }
        public Nullable<System.DateTime> ComparePeriodEnd { get; set; }
        public string Name { get; set; }
        public Nullable<bool> StatisticsFinished { get; set; }
        public string Purpose { get; set; }
        public string FinishDescription { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ERActionPlan ERActionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERImprovmentERAnalysisHeader> ERImprovmentERAnalysisHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERImprovmentERHeader> ERImprovmentERHeaders { get; set; }
        public virtual ERImprovmentResponsible ERImprovmentResponsible { get; set; }
        public virtual Office Office { get; set; }
    }
}
