//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERImprovmentERAnalysisHeader
    {
        public int Id { get; set; }
        public int ERImprovmentId { get; set; }
        public int ERAnalysisHeaderId { get; set; }
    
        public virtual ERAnalysisHeader ERAnalysisHeader { get; set; }
        public virtual ERImprovment ERImprovment { get; set; }
    }
}
