//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERReportMeasure
    {
        public int Id { get; set; }
        public int EnviromentalReportId { get; set; }
        public int ControlStatusId { get; set; }
        public string FinishUnit { get; set; }
        public Nullable<int> FinishNr { get; set; }
        public bool IsBeforeControlStatus { get; set; }
        public bool Activated { get; set; }
        public bool IsOwnMeasure { get; set; }
        public bool IsModule { get; set; }
        public bool IsStatus { get; set; }
        public Nullable<int> ERModuleId { get; set; }
        public Nullable<int> ERStatusId { get; set; }
        public Nullable<int> EROwnMeasureId { get; set; }
        public Nullable<System.DateTime> FinishBefore { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
    
        public virtual EnviromentalReport EnviromentalReport { get; set; }
        public virtual ERModule ERModule { get; set; }
        public virtual EROwnMeasure EROwnMeasure { get; set; }
        public virtual ERStatu ERStatu { get; set; }
        public virtual ERStatu ERStatu1 { get; set; }
    }
}
