//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FollowUp()
        {
            this.FollowUpEmployeePermissions = new HashSet<FollowUpEmployeePermission>();
            this.FollowUpLargeDiagramGroupRows = new HashSet<FollowUpLargeDiagramGroupRow>();
            this.FollowUpOfficeLargeDiagrams = new HashSet<FollowUpOfficeLargeDiagram>();
            this.FollowUpRows = new HashSet<FollowUpRow>();
            this.FollowUpViewGroupRows = new HashSet<FollowUpViewGroupRow>();
            this.ManualPartDocumentFollowUps = new HashSet<ManualPartDocumentFollowUp>();
            this.ManualPartDocumentLogFollowUps = new HashSet<ManualPartDocumentLogFollowUp>();
            this.ManualPartDocumentPlanFollowUps = new HashSet<ManualPartDocumentPlanFollowUp>();
            this.QRImprovments = new HashSet<QRImprovment>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int ResponsibleId { get; set; }
        public Nullable<int> ReminderNr { get; set; }
        public string ReminderUnit { get; set; }
        public string Frequency { get; set; }
        public int DiagramId { get; set; }
        public int StartYear { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartQuater { get; set; }
        public string Name { get; set; }
        public Nullable<int> GoalValue { get; set; }
        public Nullable<decimal> GoalDoubleValue { get; set; }
        public bool IsIntValue { get; set; }
        public Nullable<int> ShowOnStartPage { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> PartReport { get; set; }
        public Nullable<int> FollowUpGroupId { get; set; }
        public bool ValueOverGoal { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> StartWeek { get; set; }
        public string CompareValue1Name { get; set; }
        public string CompareValue2Name { get; set; }
        public Nullable<bool> DoNotDevideStart { get; set; }
        public string GaugueBackImage { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FollowUpDiagram FollowUpDiagram { get; set; }
        public virtual FollowUpGroup FollowUpGroup { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpEmployeePermission> FollowUpEmployeePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpLargeDiagramGroupRow> FollowUpLargeDiagramGroupRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpOfficeLargeDiagram> FollowUpOfficeLargeDiagrams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpRow> FollowUpRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpViewGroupRow> FollowUpViewGroupRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentFollowUp> ManualPartDocumentFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogFollowUp> ManualPartDocumentLogFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentPlanFollowUp> ManualPartDocumentPlanFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovment> QRImprovments { get; set; }
    }
}
