//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpRow
    {
        public int Id { get; set; }
        public int FollowUpId { get; set; }
        public Nullable<int> IntValue { get; set; }
        public Nullable<decimal> DoubleValue { get; set; }
        public int Year { get; set; }
        public Nullable<int> Quater { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> PerformedDate { get; set; }
        public Nullable<int> PerformedById { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public string DocPath { get; set; }
        public Nullable<int> GoalValue { get; set; }
        public Nullable<decimal> GoalDoubleValue { get; set; }
        public Nullable<bool> IsPartReport { get; set; }
        public Nullable<System.DateTime> PartReportToDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<decimal> CompareValue1 { get; set; }
        public Nullable<decimal> CompareValue2 { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FollowUp FollowUp { get; set; }
    }
}
