//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICErrorCodeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICErrorCodeGroup()
        {
            this.ICErrorCodes = new HashSet<ICErrorCode>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ICErrorCodeMainGroupId { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICErrorCode> ICErrorCodes { get; set; }
        public virtual ICErrorCodeMainGroup ICErrorCodeMainGroup { get; set; }
    }
}
