//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICErrorCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICErrorCode()
        {
            this.InternalControlOfficeLogRowCodes = new HashSet<InternalControlOfficeLogRowCode>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public bool Deleted { get; set; }
        public int ICErrorCodeGroupId { get; set; }
    
        public virtual ICErrorCodeGroup ICErrorCodeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLogRowCode> InternalControlOfficeLogRowCodes { get; set; }
    }
}
