//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentReportLog
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public string LogText { get; set; }
        public int IncidentReportId { get; set; }
        public string HeaderText { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual IncidentReport IncidentReport { get; set; }
    }
}
