//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlOfficeVehicleBrandGoal
    {
        public int Id { get; set; }
        public int VehicelBrandId { get; set; }
        public int InternalControlOfficeId { get; set; }
        public int GoalNr { get; set; }
        public string GoalUnit { get; set; }
    
        public virtual InternalControlOffice InternalControlOffice { get; set; }
        public virtual VehicleBrand VehicleBrand { get; set; }
    }
}
