//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalControlTemplate()
        {
            this.InternalControlOffices = new HashSet<InternalControlOffice>();
            this.InternalControlTemplateRows = new HashSet<InternalControlTemplateRow>();
            this.InternalControlTemplateSubGroups = new HashSet<InternalControlTemplateSubGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CompanyId { get; set; }
        public bool Deleted { get; set; }
        public int InternalControlTemplateGroupId { get; set; }
        public Nullable<bool> HasVehicleBrand { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOffice> InternalControlOffices { get; set; }
        public virtual InternalControlTemplateGroup InternalControlTemplateGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlTemplateRow> InternalControlTemplateRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlTemplateSubGroup> InternalControlTemplateSubGroups { get; set; }
    }
}
