//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlTemplateRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalControlTemplateRow()
        {
            this.InternalControlOfficeRows = new HashSet<InternalControlOfficeRow>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public bool Deleted { get; set; }
        public bool HasPhoto { get; set; }
        public int InternalControlTemplateId { get; set; }
        public Nullable<int> InternalControlTemplateSubGroupId { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeRow> InternalControlOfficeRows { get; set; }
        public virtual InternalControlTemplate InternalControlTemplate { get; set; }
        public virtual InternalControlTemplateSubGroup InternalControlTemplateSubGroup { get; set; }
    }
}
