//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlOfficeRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalControlOfficeRow()
        {
            this.InternalControlOfficeLogRows = new HashSet<InternalControlOfficeLogRow>();
        }
    
        public int Id { get; set; }
        public int InternalControlOfficeId { get; set; }
        public string RowText { get; set; }
        public Nullable<int> InternalControlTemplateRowId { get; set; }
        public Nullable<int> OfficeDepartmentTaskId { get; set; }
        public Nullable<int> InternalControlOfficeSubGroupId { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
    
        public virtual InternalControlOffice InternalControlOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLogRow> InternalControlOfficeLogRows { get; set; }
        public virtual InternalControlOfficeSubGroup InternalControlOfficeSubGroup { get; set; }
        public virtual InternalControlTemplateRow InternalControlTemplateRow { get; set; }
        public virtual OfficeDepartmentTask OfficeDepartmentTask { get; set; }
    }
}
