//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlOfficeLogRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalControlOfficeLogRow()
        {
            this.InternalControlOfficeLogRowCodes = new HashSet<InternalControlOfficeLogRowCode>();
            this.InternalControlOfficeLogRowFiles = new HashSet<InternalControlOfficeLogRowFile>();
        }
    
        public int Id { get; set; }
        public int InternalControlOfficeLogId { get; set; }
        public string Text { get; set; }
        public bool IsYes { get; set; }
        public bool IsNo { get; set; }
        public bool IsEa { get; set; }
        public string FilePath { get; set; }
        public string Comment { get; set; }
        public Nullable<int> QRReportId { get; set; }
        public Nullable<int> InternalControlOfficeRowId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual InternalControlOfficeLog InternalControlOfficeLog { get; set; }
        public virtual InternalControlOfficeRow InternalControlOfficeRow { get; set; }
        public virtual QualityReport QualityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLogRowCode> InternalControlOfficeLogRowCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLogRowFile> InternalControlOfficeLogRowFiles { get; set; }
    }
}
