//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlOfficeLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalControlOfficeLog()
        {
            this.InternalControlOfficeLogRows = new HashSet<InternalControlOfficeLogRow>();
        }
    
        public int Id { get; set; }
        public int InternalControlOfficeId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> VehicleBrandId { get; set; }
        public Nullable<bool> IsPartSaved { get; set; }
        public string RegNr { get; set; }
        public string AoNr { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> CreatedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual InternalControlOffice InternalControlOffice { get; set; }
        public virtual VehicleBrand VehicleBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLogRow> InternalControlOfficeLogRows { get; set; }
    }
}
