//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalControlOffice()
        {
            this.InternalControlOfficeLogs = new HashSet<InternalControlOfficeLog>();
            this.InternalControlOfficeRows = new HashSet<InternalControlOfficeRow>();
            this.InternalControlOfficeSubGroups = new HashSet<InternalControlOfficeSubGroup>();
            this.InternalControlOfficeVehicleBrandGoals = new HashSet<InternalControlOfficeVehicleBrandGoal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> InternalControlTemplateId { get; set; }
        public bool Deleted { get; set; }
        public string TimeUnit { get; set; }
        public Nullable<int> TimeNr { get; set; }
        public Nullable<System.DateTime> Next { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
        public Nullable<int> AmountBudget { get; set; }
        public string AmountUnit { get; set; }
        public Nullable<bool> HasVehicleBrand { get; set; }
        public Nullable<bool> UseEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual InternalControlTemplate InternalControlTemplate { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLog> InternalControlOfficeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeRow> InternalControlOfficeRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeSubGroup> InternalControlOfficeSubGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeVehicleBrandGoal> InternalControlOfficeVehicleBrandGoals { get; set; }
    }
}
