//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalControlTemplateSubGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalControlTemplateSubGroup()
        {
            this.InternalControlOfficeSubGroups = new HashSet<InternalControlOfficeSubGroup>();
            this.InternalControlTemplateRows = new HashSet<InternalControlTemplateRow>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int InternalControlTemplateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeSubGroup> InternalControlOfficeSubGroups { get; set; }
        public virtual InternalControlTemplate InternalControlTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlTemplateRow> InternalControlTemplateRows { get; set; }
    }
}
