//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualPartSuggestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManualPartSuggestion()
        {
            this.ManualPartSuggestion1 = new HashSet<ManualPartSuggestion>();
            this.ManualPartSuggestionDocuments = new HashSet<ManualPartSuggestionDocument>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ManualPartTemplateId { get; set; }
        public int ToOfficeId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool PartOfManualSuggestion { get; set; }
        public int ManualSuggestionId { get; set; }
        public int Position { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string PartContent { get; set; }
        public bool IsOnlyHeader { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartSuggestion> ManualPartSuggestion1 { get; set; }
        public virtual ManualPartSuggestion ManualPartSuggestion2 { get; set; }
        public virtual ManualPartTemplate ManualPartTemplate { get; set; }
        public virtual ManualSuggestion ManualSuggestion { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartSuggestionDocument> ManualPartSuggestionDocuments { get; set; }
    }
}
