//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualPartDocumentLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManualPartDocumentLog()
        {
            this.ManualPartDocumentLogAttachedFiles = new HashSet<ManualPartDocumentLogAttachedFile>();
            this.ManualPartDocumentLogAttachedLogs = new HashSet<ManualPartDocumentLogAttachedLog>();
            this.ManualPartDocumentLogAttachedLogs1 = new HashSet<ManualPartDocumentLogAttachedLog>();
            this.ManualPartDocumentLogEmployees = new HashSet<ManualPartDocumentLogEmployee>();
            this.ManualPartDocumentLogFollowUps = new HashSet<ManualPartDocumentLogFollowUp>();
            this.ManualPartDocumentLogImprovements = new HashSet<ManualPartDocumentLogImprovement>();
        }
    
        public int Id { get; set; }
        public int ManualPartDocumentId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public bool Deleted { get; set; }
        public string DocPath { get; set; }
        public string Information { get; set; }
        public Nullable<bool> ShowInWeb { get; set; }
        public string PartContent { get; set; }
        public Nullable<System.DateTime> FinalApprovedDate { get; set; }
        public Nullable<int> FinalApprovedBy { get; set; }
        public Nullable<bool> ParticipantSignature { get; set; }
        public Nullable<int> ManualRadDocumentId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ManualPartDocument ManualPartDocument { get; set; }
        public virtual ManualRadDocument ManualRadDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogAttachedFile> ManualPartDocumentLogAttachedFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogAttachedLog> ManualPartDocumentLogAttachedLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogAttachedLog> ManualPartDocumentLogAttachedLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogEmployee> ManualPartDocumentLogEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogFollowUp> ManualPartDocumentLogFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogImprovement> ManualPartDocumentLogImprovements { get; set; }
    }
}
