//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualPartDocumentPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManualPartDocumentPlan()
        {
            this.ManualPartDocumentPlanAttachedFiles = new HashSet<ManualPartDocumentPlanAttachedFile>();
            this.ManualPartDocumentPlanEmployees = new HashSet<ManualPartDocumentPlanEmployee>();
            this.ManualPartDocumentPlanFollowUps = new HashSet<ManualPartDocumentPlanFollowUp>();
        }
    
        public int Id { get; set; }
        public int ManualPartDocumentId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public string PartContent { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public string DocPath { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> ManualRadDocumentId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ManualPartDocument ManualPartDocument { get; set; }
        public virtual ManualRadDocument ManualRadDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentPlanAttachedFile> ManualPartDocumentPlanAttachedFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentPlanEmployee> ManualPartDocumentPlanEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentPlanFollowUp> ManualPartDocumentPlanFollowUps { get; set; }
    }
}
