//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualPartDocumentLogImprovement
    {
        public int Id { get; set; }
        public int ManualPartDocumentLogId { get; set; }
        public int QrImprovmentId { get; set; }
    
        public virtual ManualPartDocumentLog ManualPartDocumentLog { get; set; }
        public virtual QRImprovment QRImprovment { get; set; }
    }
}
