//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manual()
        {
            this.ManualOfficeFastLinks = new HashSet<ManualOfficeFastLink>();
            this.ManualParts = new HashSet<ManualPart>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OfficeId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
        public string Type { get; set; }
        public Nullable<int> ManualTemplateId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ManualTemplate ManualTemplate { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualOfficeFastLink> ManualOfficeFastLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPart> ManualParts { get; set; }
    }
}
