//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualPartDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManualPartDocument()
        {
            this.ManualOfficeFastLinks = new HashSet<ManualOfficeFastLink>();
            this.ManualPartDocumentEmployees = new HashSet<ManualPartDocumentEmployee>();
            this.ManualPartDocumentFollowUps = new HashSet<ManualPartDocumentFollowUp>();
            this.ManualPartDocumentLogs = new HashSet<ManualPartDocumentLog>();
            this.ManualPartDocumentPlans = new HashSet<ManualPartDocumentPlan>();
            this.Offices = new HashSet<Office>();
            this.PropertyManualPartDocuments = new HashSet<PropertyManualPartDocument>();
            this.Tools = new HashSet<Tool>();
            this.ToolManualPartDocuments = new HashSet<ToolManualPartDocument>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ManualPartId { get; set; }
        public Nullable<int> ManualDocumentId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public string DocDesc { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
        public Nullable<int> TimeNr { get; set; }
        public string TimeUnit { get; set; }
        public Nullable<System.DateTime> Next { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> OfficeDepartmentTaskId { get; set; }
        public Nullable<int> OfficeDepartmentId { get; set; }
        public Nullable<int> OfficeDepartmentTaskGroupId { get; set; }
        public Nullable<int> ManualDocumentTemplateCompanyId { get; set; }
        public Nullable<int> ManualDocumentPDFCompanyId { get; set; }
        public Nullable<bool> IsOnlyReadable { get; set; }
        public Nullable<bool> ParticipantSignature { get; set; }
        public Nullable<bool> UseNewBookingWindow { get; set; }
        public Nullable<bool> ShowInFollowUpPopup { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ManualDocument ManualDocument { get; set; }
        public virtual ManualDocumentPDFCompany ManualDocumentPDFCompany { get; set; }
        public virtual ManualDocumentTemplateCompany ManualDocumentTemplateCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualOfficeFastLink> ManualOfficeFastLinks { get; set; }
        public virtual ManualPart ManualPart { get; set; }
        public virtual OfficeDepartment OfficeDepartment { get; set; }
        public virtual OfficeDepartmentTask OfficeDepartmentTask { get; set; }
        public virtual OfficeDepartmentTaskGroup OfficeDepartmentTaskGroup { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentEmployee> ManualPartDocumentEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentFollowUp> ManualPartDocumentFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLog> ManualPartDocumentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentPlan> ManualPartDocumentPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Office> Offices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyManualPartDocument> PropertyManualPartDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolManualPartDocument> ToolManualPartDocuments { get; set; }
    }
}
