//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualOfficeFastLink
    {
        public int Id { get; set; }
        public Nullable<int> ManualPartId { get; set; }
        public Nullable<int> ManualPartDocumentId { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> OfficeDepartmentId { get; set; }
        public Nullable<int> OfficeDepartmentTaskId { get; set; }
        public Nullable<int> OfficeDepartmentTaskGroupId { get; set; }
        public Nullable<int> ManualId { get; set; }
    
        public virtual Manual Manual { get; set; }
        public virtual ManualPart ManualPart { get; set; }
        public virtual ManualPartDocument ManualPartDocument { get; set; }
        public virtual OfficeDepartment OfficeDepartment { get; set; }
        public virtual OfficeDepartmentTask OfficeDepartmentTask { get; set; }
        public virtual OfficeDepartmentTaskGroup OfficeDepartmentTaskGroup { get; set; }
        public virtual Office Office { get; set; }
    }
}
