//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualPartTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManualPartTemplate()
        {
            this.ManualParts = new HashSet<ManualPart>();
            this.ManualPartSuggestions = new HashSet<ManualPartSuggestion>();
            this.ManualPartTemplate1 = new HashSet<ManualPartTemplate>();
            this.ManualPartTemplateDocuments = new HashSet<ManualPartTemplateDocument>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PartContent { get; set; }
        public int ManualTemplateId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Position { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public bool Deleted { get; set; }
        public string UserComment { get; set; }
        public bool IsOnlyHeader { get; set; }
        public string PrivateComment { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPart> ManualParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartSuggestion> ManualPartSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartTemplate> ManualPartTemplate1 { get; set; }
        public virtual ManualPartTemplate ManualPartTemplate2 { get; set; }
        public virtual ManualTemplate ManualTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartTemplateDocument> ManualPartTemplateDocuments { get; set; }
    }
}
