//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualPartDocumentLogAttachedLog
    {
        public int Id { get; set; }
        public int MainLogId { get; set; }
        public int AttachedLogId { get; set; }
    
        public virtual ManualPartDocumentLog ManualPartDocumentLog { get; set; }
        public virtual ManualPartDocumentLog ManualPartDocumentLog1 { get; set; }
    }
}
