//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualSuggestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManualSuggestion()
        {
            this.ManualPartSuggestions = new HashSet<ManualPartSuggestion>();
        }
    
        public int Id { get; set; }
        public int ToOfficeId { get; set; }
        public int ManualTemplateId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Name { get; set; }
        public bool Deleted { get; set; }
        public bool SendToCustomer { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartSuggestion> ManualPartSuggestions { get; set; }
        public virtual ManualTemplate ManualTemplate { get; set; }
        public virtual Office Office { get; set; }
    }
}
