//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePartOffice
    {
        public int OfficeId { get; set; }
        public int ModulePartId { get; set; }
        public string ShowName { get; set; }
        public bool Activated { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ModulePart ModulePart { get; set; }
        public virtual Office Office { get; set; }
    }
}
