//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModulePart()
        {
            this.BisoftProgramUpdates = new HashSet<BisoftProgramUpdate>();
            this.ModulePartCompanies = new HashSet<ModulePartCompany>();
            this.ModulePartEmployees = new HashSet<ModulePartEmployee>();
            this.ModulePartOffices = new HashSet<ModulePartOffice>();
        }
    
        public int Id { get; set; }
        public int ModuleId { get; set; }
        public string Name { get; set; }
        public string StartAddress { get; set; }
        public bool IsStart { get; set; }
        public string Icon { get; set; }
        public string ExtendedPermissionText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BisoftProgramUpdate> BisoftProgramUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePartCompany> ModulePartCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePartEmployee> ModulePartEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePartOffice> ModulePartOffices { get; set; }
        public virtual Module Module { get; set; }
    }
}
