//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.BisoftProgramUpdates = new HashSet<BisoftProgramUpdate>();
            this.EmailSents = new HashSet<EmailSent>();
            this.ModuleCompanies = new HashSet<ModuleCompany>();
            this.ModuleEmployees = new HashSet<ModuleEmployee>();
            this.ModuleOffices = new HashSet<ModuleOffice>();
            this.ModuleParts = new HashSet<ModulePart>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string StartAddress { get; set; }
        public string Icon { get; set; }
        public string Color { get; set; }
        public string BorderColor { get; set; }
        public bool IsStart { get; set; }
        public string Description { get; set; }
        public string AltName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BisoftProgramUpdate> BisoftProgramUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSent> EmailSents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleCompany> ModuleCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleEmployee> ModuleEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleOffice> ModuleOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePart> ModuleParts { get; set; }
    }
}
