//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePartEmployee
    {
        public int OfficeId { get; set; }
        public int EmployeeId { get; set; }
        public int ModulePartId { get; set; }
        public bool Activated { get; set; }
        public Nullable<bool> SeeAll { get; set; }
        public Nullable<bool> OnlyRead { get; set; }
        public Nullable<bool> ShowToolPrices { get; set; }
        public Nullable<bool> SeeMyOfficeDepartment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ModulePart ModulePart { get; set; }
        public virtual Office Office { get; set; }
    }
}
