//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeDepartmentTaskGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfficeDepartmentTaskGroup()
        {
            this.CustomerReportPositives = new HashSet<CustomerReportPositive>();
            this.ManualOfficeFastLinks = new HashSet<ManualOfficeFastLink>();
            this.ManualParts = new HashSet<ManualPart>();
            this.ManualPartDocuments = new HashSet<ManualPartDocument>();
            this.OfficeDepartmentTaskGroupRows = new HashSet<OfficeDepartmentTaskGroupRow>();
            this.OfficeDepartmentTaskGroupVersions = new HashSet<OfficeDepartmentTaskGroupVersion>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public string Name { get; set; }
        public string PartContent { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportPositive> CustomerReportPositives { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualOfficeFastLink> ManualOfficeFastLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPart> ManualParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocument> ManualPartDocuments { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskGroupRow> OfficeDepartmentTaskGroupRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskGroupVersion> OfficeDepartmentTaskGroupVersions { get; set; }
    }
}
