//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office()
        {
            this.ACOilTypes = new HashSet<ACOilType>();
            this.ACReports = new HashSet<ACReport>();
            this.ACReportGas = new HashSet<ACReportGa>();
            this.BisoftWeekEmails = new HashSet<BisoftWeekEmail>();
            this.CarPreSales = new HashSet<CarPreSale>();
            this.CarPreSaleFlowGroups = new HashSet<CarPreSaleFlowGroup>();
            this.CarPreSaleModuleFlows = new HashSet<CarPreSaleModuleFlow>();
            this.CarPreSalesModuleOffices = new HashSet<CarPreSalesModuleOffice>();
            this.CBRProviderOffices = new HashSet<CBRProviderOffice>();
            this.CRLogMeasureReports = new HashSet<CRLogMeasureReport>();
            this.CRModuleEmailNotifications = new HashSet<CRModuleEmailNotification>();
            this.CRModulesOffices = new HashSet<CRModulesOffice>();
            this.CRPositiveGroups = new HashSet<CRPositiveGroup>();
            this.CRResponsibles = new HashSet<CRResponsible>();
            this.CRStatusEmailNotifications = new HashSet<CRStatusEmailNotification>();
            this.CRStatusOffices = new HashSet<CRStatusOffice>();
            this.CustomerPositiveGrades = new HashSet<CustomerPositiveGrade>();
            this.CustomerReportImprovments = new HashSet<CustomerReportImprovment>();
            this.CustomerReportPositives = new HashSet<CustomerReportPositive>();
            this.CustomerReports = new HashSet<CustomerReport>();
            this.EmailContacts = new HashSet<EmailContact>();
            this.EmailSents = new HashSet<EmailSent>();
            this.EmailSettingsOffices = new HashSet<EmailSettingsOffice>();
            this.EmployeeGroups = new HashSet<EmployeeGroup>();
            this.Employees = new HashSet<Employee>();
            this.EnviromentalReports = new HashSet<EnviromentalReport>();
            this.ERActionPlans = new HashSet<ERActionPlan>();
            this.ERImprovmentResponsibles = new HashSet<ERImprovmentResponsible>();
            this.ERImprovments = new HashSet<ERImprovment>();
            this.ERModuleOffices = new HashSet<ERModuleOffice>();
            this.EROwnMeasures = new HashSet<EROwnMeasure>();
            this.ERResponsibles = new HashSet<ERResponsible>();
            this.ERStatusEmailNotifications = new HashSet<ERStatusEmailNotification>();
            this.ERStatusOffices = new HashSet<ERStatusOffice>();
            this.FollowUps = new HashSet<FollowUp>();
            this.FollowUpGroups = new HashSet<FollowUpGroup>();
            this.FollowUpLargeDiagramGroups = new HashSet<FollowUpLargeDiagramGroup>();
            this.FollowUpOfficeLargeDiagrams = new HashSet<FollowUpOfficeLargeDiagram>();
            this.FollowUpViewGroups = new HashSet<FollowUpViewGroup>();
            this.IncidentReports = new HashSet<IncidentReport>();
            this.IncidentReportLocations = new HashSet<IncidentReportLocation>();
            this.IncidentReportWorkTasks = new HashSet<IncidentReportWorkTask>();
            this.InternalControlOffices = new HashSet<InternalControlOffice>();
            this.InternalControlOfficeGroups = new HashSet<InternalControlOfficeGroup>();
            this.Manuals = new HashSet<Manual>();
            this.ManualAdminOfficeConnections = new HashSet<ManualAdminOfficeConnection>();
            this.ManualOfficeFastLinks = new HashSet<ManualOfficeFastLink>();
            this.ManualPartDocuments = new HashSet<ManualPartDocument>();
            this.ManualPartSuggestions = new HashSet<ManualPartSuggestion>();
            this.ManualSuggestions = new HashSet<ManualSuggestion>();
            this.ModuleEmployees = new HashSet<ModuleEmployee>();
            this.ModuleOffices = new HashSet<ModuleOffice>();
            this.ModulePartEmployees = new HashSet<ModulePartEmployee>();
            this.ModulePartOffices = new HashSet<ModulePartOffice>();
            this.OfficeDepartments = new HashSet<OfficeDepartment>();
            this.OfficeDepartmentTaskGroups = new HashSet<OfficeDepartmentTaskGroup>();
            this.OfficeInternalRevPlaningSettings = new HashSet<OfficeInternalRevPlaningSetting>();
            this.OfficeKeyCabinets = new HashSet<OfficeKeyCabinet>();
            this.OfficeManagementReviewSettings = new HashSet<OfficeManagementReviewSetting>();
            this.OfficeManualDocuments = new HashSet<OfficeManualDocument>();
            this.OfficeParkings = new HashSet<OfficeParking>();
            this.OfficeSafetyEmployees = new HashSet<OfficeSafetyEmployee>();
            this.OfficeWebLinks = new HashSet<OfficeWebLink>();
            this.OfficeVehicleBrandResponsibles = new HashSet<OfficeVehicleBrandResponsible>();
            this.Properties = new HashSet<Property>();
            this.PropertyControlDocuments = new HashSet<PropertyControlDocument>();
            this.PropertyGroups = new HashSet<PropertyGroup>();
            this.PropertyInspectionDocuments = new HashSet<PropertyInspectionDocument>();
            this.PropertyMaintenanceDocuments = new HashSet<PropertyMaintenanceDocument>();
            this.PropertySettingsOffices = new HashSet<PropertySettingsOffice>();
            this.QRActionPlans = new HashSet<QRActionPlan>();
            this.QRImportTaskExternalSystems = new HashSet<QRImportTaskExternalSystem>();
            this.QRImprovmentResponsibles = new HashSet<QRImprovmentResponsible>();
            this.QRImprovments = new HashSet<QRImprovment>();
            this.QRModuleEmailNotifications = new HashSet<QRModuleEmailNotification>();
            this.QRModuleOffices = new HashSet<QRModuleOffice>();
            this.QROfficeGoals = new HashSet<QROfficeGoal>();
            this.QROwnMeasures = new HashSet<QROwnMeasure>();
            this.QRResponsibles = new HashSet<QRResponsible>();
            this.QRStatusEmailNotifications = new HashSet<QRStatusEmailNotification>();
            this.QRStatusOffices = new HashSet<QRStatusOffice>();
            this.QualityReports = new HashSet<QualityReport>();
            this.RiskAnalysisOffices = new HashSet<RiskAnalysisOffice>();
            this.SwedAssessmentSkillsERs = new HashSet<SwedAssessmentSkillsER>();
            this.SwedAssessmentSkillsIBs = new HashSet<SwedAssessmentSkillsIB>();
            this.SwedAssessmentSkillsIRs = new HashSet<SwedAssessmentSkillsIR>();
            this.SwedAssessmentSkillsKAs = new HashSet<SwedAssessmentSkillsKA>();
            this.SwedAssessmentSkillsKKs = new HashSet<SwedAssessmentSkillsKK>();
            this.SwedAssessmentSkillsTAs = new HashSet<SwedAssessmentSkillsTA>();
            this.SwedAssessmentSkillsUAs = new HashSet<SwedAssessmentSkillsUA>();
            this.SwedDocumentReviews = new HashSet<SwedDocumentReview>();
            this.SwedERSamplingCars = new HashSet<SwedERSamplingCar>();
            this.SwedJointInfoEducations = new HashSet<SwedJointInfoEducation>();
            this.SwedManagementReview381 = new HashSet<SwedManagementReview381>();
            this.SwedOfficeAreas = new HashSet<SwedOfficeArea>();
            this.SwedPowerOfAttorneyERs = new HashSet<SwedPowerOfAttorneyER>();
            this.Tools = new HashSet<Tool>();
            this.Tools1 = new HashSet<Tool>();
            this.ToolBorroweds = new HashSet<ToolBorrowed>();
            this.ToolCalibrationMethods = new HashSet<ToolCalibrationMethod>();
            this.ToolCostOffices = new HashSet<ToolCostOffice>();
            this.ToolDepartments = new HashSet<ToolDepartment>();
            this.ToolDocuments = new HashSet<ToolDocument>();
            this.ToolGroups = new HashSet<ToolGroup>();
            this.ToolGroupInventories = new HashSet<ToolGroupInventory>();
            this.ToolLogs = new HashSet<ToolLog>();
            this.ToolMaintenanceRutineOffices = new HashSet<ToolMaintenanceRutineOffice>();
            this.ToolProductPriceOffices = new HashSet<ToolProductPriceOffice>();
            this.ToolSettingsOffices = new HashSet<ToolSettingsOffice>();
            this.ToolSettingsOffices1 = new HashSet<ToolSettingsOffice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public int CompanyId { get; set; }
        public bool Status { get; set; }
        public string AckrNr { get; set; }
        public string OrgNr { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ManualPartDocumentId { get; set; }
        public Nullable<bool> CanHaveAgreement { get; set; }
        public Nullable<int> OfficeGroupId { get; set; }
        public string ACClass { get; set; }
        public string CertNr { get; set; }
        public string InfoText { get; set; }
        public int HighLimit { get; set; }
        public int MediumLimit { get; set; }
        public Nullable<bool> BlockCancelFinalAproval { get; set; }
        public Nullable<int> CompanyRegionId { get; set; }
        public string Custnr { get; set; }
        public string FaktRef { get; set; }
        public Nullable<int> ContactPersonId { get; set; }
        public Nullable<bool> LoanOffice { get; set; }
        public Nullable<bool> HasBAMImport { get; set; }
        public string HouseOwner { get; set; }
        public string HouseCareTaker { get; set; }
        public Nullable<int> TotalArea { get; set; }
        public Nullable<int> AreaForRent { get; set; }
        public Nullable<int> CarLanes { get; set; }
        public Nullable<int> MCLanes { get; set; }
        public Nullable<int> HeavyLanes { get; set; }
        public Nullable<int> TandemLanes { get; set; }
        public string HbToken { get; set; }
        public string HouseOwnerPhone { get; set; }
        public string HouseCareTakerPhone { get; set; }
        public string HouseOwnerEmail { get; set; }
        public string HouseCareTakerEmail { get; set; }
        public string HouseOwnerReportName { get; set; }
        public string HouseOwnerReportEmail { get; set; }
        public string HouseOwnerReportPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACOilType> ACOilTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACReport> ACReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACReportGa> ACReportGas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BisoftWeekEmail> BisoftWeekEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSaleFlowGroup> CarPreSaleFlowGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSaleModuleFlow> CarPreSaleModuleFlows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSalesModuleOffice> CarPreSalesModuleOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CBRProviderOffice> CBRProviderOffices { get; set; }
        public virtual Company Company { get; set; }
        public virtual CompanyRegion CompanyRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRLogMeasureReport> CRLogMeasureReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRModuleEmailNotification> CRModuleEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRModulesOffice> CRModulesOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRPositiveGroup> CRPositiveGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRResponsible> CRResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRStatusEmailNotification> CRStatusEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRStatusOffice> CRStatusOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPositiveGrade> CustomerPositiveGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportImprovment> CustomerReportImprovments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportPositive> CustomerReportPositives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReport> CustomerReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailContact> EmailContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSent> EmailSents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSettingsOffice> EmailSettingsOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGroup> EmployeeGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnviromentalReport> EnviromentalReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERActionPlan> ERActionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERImprovmentResponsible> ERImprovmentResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERImprovment> ERImprovments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERModuleOffice> ERModuleOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EROwnMeasure> EROwnMeasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERResponsible> ERResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERStatusEmailNotification> ERStatusEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERStatusOffice> ERStatusOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUp> FollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpGroup> FollowUpGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpLargeDiagramGroup> FollowUpLargeDiagramGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpOfficeLargeDiagram> FollowUpOfficeLargeDiagrams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpViewGroup> FollowUpViewGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReport> IncidentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportLocation> IncidentReportLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReportWorkTask> IncidentReportWorkTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOffice> InternalControlOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeGroup> InternalControlOfficeGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manual> Manuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualAdminOfficeConnection> ManualAdminOfficeConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualOfficeFastLink> ManualOfficeFastLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocument> ManualPartDocuments { get; set; }
        public virtual ManualPartDocument ManualPartDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartSuggestion> ManualPartSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualSuggestion> ManualSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleEmployee> ModuleEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleOffice> ModuleOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePartEmployee> ModulePartEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulePartOffice> ModulePartOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartment> OfficeDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskGroup> OfficeDepartmentTaskGroups { get; set; }
        public virtual OfficeGroup OfficeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeInternalRevPlaningSetting> OfficeInternalRevPlaningSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeKeyCabinet> OfficeKeyCabinets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeManagementReviewSetting> OfficeManagementReviewSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeManualDocument> OfficeManualDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeParking> OfficeParkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeSafetyEmployee> OfficeSafetyEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeWebLink> OfficeWebLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeVehicleBrandResponsible> OfficeVehicleBrandResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyControlDocument> PropertyControlDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyGroup> PropertyGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyInspectionDocument> PropertyInspectionDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyMaintenanceDocument> PropertyMaintenanceDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertySettingsOffice> PropertySettingsOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRActionPlan> QRActionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImportTaskExternalSystem> QRImportTaskExternalSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovmentResponsible> QRImprovmentResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovment> QRImprovments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRModuleEmailNotification> QRModuleEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRModuleOffice> QRModuleOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QROfficeGoal> QROfficeGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QROwnMeasure> QROwnMeasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRResponsible> QRResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRStatusEmailNotification> QRStatusEmailNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRStatusOffice> QRStatusOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityReport> QualityReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOffice> RiskAnalysisOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsER> SwedAssessmentSkillsERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsIB> SwedAssessmentSkillsIBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsIR> SwedAssessmentSkillsIRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsKA> SwedAssessmentSkillsKAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsKK> SwedAssessmentSkillsKKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsTA> SwedAssessmentSkillsTAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedAssessmentSkillsUA> SwedAssessmentSkillsUAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedDocumentReview> SwedDocumentReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedERSamplingCar> SwedERSamplingCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedJointInfoEducation> SwedJointInfoEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedManagementReview381> SwedManagementReview381 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedOfficeArea> SwedOfficeAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedPowerOfAttorneyER> SwedPowerOfAttorneyERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolBorrowed> ToolBorroweds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationMethod> ToolCalibrationMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCostOffice> ToolCostOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolDepartment> ToolDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolDocument> ToolDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolGroup> ToolGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolGroupInventory> ToolGroupInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolLog> ToolLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceRutineOffice> ToolMaintenanceRutineOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolProductPriceOffice> ToolProductPriceOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolSettingsOffice> ToolSettingsOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolSettingsOffice> ToolSettingsOffices1 { get; set; }
    }
}
