//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeDepartmentTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfficeDepartmentTask()
        {
            this.CQReportTaskRows = new HashSet<CQReportTaskRow>();
            this.CRPositiveDepartmentTasks = new HashSet<CRPositiveDepartmentTask>();
            this.InternalControlOfficeRows = new HashSet<InternalControlOfficeRow>();
            this.ManualOfficeFastLinks = new HashSet<ManualOfficeFastLink>();
            this.ManualParts = new HashSet<ManualPart>();
            this.ManualPartDocuments = new HashSet<ManualPartDocument>();
            this.OfficeDepartmentTaskGroupRows = new HashSet<OfficeDepartmentTaskGroupRow>();
            this.OfficeDepartmentTaskVersions = new HashSet<OfficeDepartmentTaskVersion>();
            this.QRImportTaskExternalSystems = new HashSet<QRImportTaskExternalSystem>();
            this.QRImprovmentTasks = new HashSet<QRImprovmentTask>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OfficeDepartmentId { get; set; }
        public bool Deleted { get; set; }
        public string PartContent { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQReportTaskRow> CQReportTaskRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRPositiveDepartmentTask> CRPositiveDepartmentTasks { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeRow> InternalControlOfficeRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualOfficeFastLink> ManualOfficeFastLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPart> ManualParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocument> ManualPartDocuments { get; set; }
        public virtual OfficeDepartment OfficeDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskGroupRow> OfficeDepartmentTaskGroupRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeDepartmentTaskVersion> OfficeDepartmentTaskVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImportTaskExternalSystem> QRImportTaskExternalSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovmentTask> QRImprovmentTasks { get; set; }
    }
}
