//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeVehicleBrandResponsible
    {
        public int Id { get; set; }
        public int VehicleBrandId { get; set; }
        public int OfficeId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        public virtual VehicleBrand VehicleBrand { get; set; }
    }
}
