//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyLog
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime PerformedDate { get; set; }
        public string Description { get; set; }
        public int LogTypeId { get; set; }
        public int PropertyId { get; set; }
        public bool Deleted { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> PropertyControlLogId { get; set; }
        public Nullable<int> PropertyInspectionLogId { get; set; }
        public Nullable<int> PropertyMaintenaceLogId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Property Property { get; set; }
        public virtual PropertyControlLog PropertyControlLog { get; set; }
        public virtual PropertyInspectionLog PropertyInspectionLog { get; set; }
        public virtual PropertyLogType PropertyLogType { get; set; }
        public virtual PropertyMaintenanceLog PropertyMaintenanceLog { get; set; }
    }
}
