//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertySettingsOffice
    {
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> InspectionReminderNr { get; set; }
        public string InspectionReminderUnit { get; set; }
        public Nullable<int> MaintenanceReminderNr { get; set; }
        public string MaintenanceReminderUnit { get; set; }
        public Nullable<int> ControlReminderNr { get; set; }
        public string ControlReminderUnit { get; set; }
    
        public virtual Office Office { get; set; }
    }
}
