//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyGroupRows = new HashSet<PropertyGroupRow>();
            this.PropertyLogs = new HashSet<PropertyLog>();
            this.PropertyManualPartDocuments = new HashSet<PropertyManualPartDocument>();
        }
    
        public int Id { get; set; }
        public string InternalId { get; set; }
        public string Product { get; set; }
        public string SerieNr { get; set; }
        public int ResponsibleId { get; set; }
        public string ExternalNr { get; set; }
        public string ControlIntervalUnit { get; set; }
        public Nullable<int> ControlIntervalNr { get; set; }
        public Nullable<int> ControlDocumentId { get; set; }
        public Nullable<System.DateTime> ControlNext { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public int Nr { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DepartmentPlaceId { get; set; }
        public string InspectionIntervalUnit { get; set; }
        public Nullable<int> InspectionIntervalNr { get; set; }
        public Nullable<int> InspectionDocumentId { get; set; }
        public Nullable<System.DateTime> InspectionNext { get; set; }
        public string MaintenanceIntervalUnit { get; set; }
        public Nullable<int> MaintenanceIntervalNr { get; set; }
        public Nullable<int> MaintenanceDocumentId { get; set; }
        public Nullable<System.DateTime> MaintenanceNext { get; set; }
        public bool HasControl { get; set; }
        public bool HasInspection { get; set; }
        public bool HasMaintenance { get; set; }
        public string MaintenanceInfo { get; set; }
        public string InspectionInfo { get; set; }
        public string ControlInfo { get; set; }
        public Nullable<System.DateTime> BoughtDate { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> InspectionResponsibleId { get; set; }
        public Nullable<int> MaintenanceResponsibleId { get; set; }
        public Nullable<int> ControlResponsibleId { get; set; }
        public Nullable<int> DepartmentPlaceLocationId { get; set; }
        public Nullable<int> PropertyProductId { get; set; }
        public Nullable<int> PropertyProductTypeId { get; set; }
        public Nullable<bool> IsOutOfOrder { get; set; }
        public string InfoText { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public Nullable<bool> HasDefect { get; set; }
        public Nullable<bool> InspectionWithDefect { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Office Office { get; set; }
        public virtual PropertyControlDocument PropertyControlDocument { get; set; }
        public virtual PropertyInspectionDocument PropertyInspectionDocument { get; set; }
        public virtual PropertyMaintenanceDocument PropertyMaintenanceDocument { get; set; }
        public virtual PropertyProduct PropertyProduct { get; set; }
        public virtual PropertyProductType PropertyProductType { get; set; }
        public virtual PropertyStatu PropertyStatu { get; set; }
        public virtual ToolDepartment ToolDepartment { get; set; }
        public virtual ToolDepartmentPlace ToolDepartmentPlace { get; set; }
        public virtual ToolDepartmentPlaceLocation ToolDepartmentPlaceLocation { get; set; }
        public virtual ToolManufacturer ToolManufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyGroupRow> PropertyGroupRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyLog> PropertyLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyManualPartDocument> PropertyManualPartDocuments { get; set; }
    }
}
