//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRActionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QRActionPlan()
        {
            this.QRActionPlanQRAnalysisHeaders = new HashSet<QRActionPlanQRAnalysisHeader>();
            this.QRActionPlanQRHeaders = new HashSet<QRActionPlanQRHeader>();
            this.QRImprovments = new HashSet<QRImprovment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Purpose { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public int OfficeId { get; set; }
        public Nullable<System.DateTime> CompareStart { get; set; }
        public Nullable<System.DateTime> CompareEnd { get; set; }
        public Nullable<int> ImpromentMoneyPercent { get; set; }
        public Nullable<int> ImprovmentNrPercent { get; set; }
        public System.DateTime ImplementStart { get; set; }
        public System.DateTime ImplementEnd { get; set; }
        public int ResponsibleId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        public virtual QRResponsible QRResponsible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRActionPlanQRAnalysisHeader> QRActionPlanQRAnalysisHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRActionPlanQRHeader> QRActionPlanQRHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovment> QRImprovments { get; set; }
    }
}
