//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRActionPlanQRHeader
    {
        public int Id { get; set; }
        public int QRHeaderId { get; set; }
        public int QRActionPlanId { get; set; }
    
        public virtual QRActionPlan QRActionPlan { get; set; }
        public virtual QRHeader QRHeader { get; set; }
    }
}
