//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRImprovment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QRImprovment()
        {
            this.ManualPartDocumentLogImprovements = new HashSet<ManualPartDocumentLogImprovement>();
            this.QRImprovementCRHeaders = new HashSet<QRImprovementCRHeader>();
            this.QRImprovmentDocuments = new HashSet<QRImprovmentDocument>();
            this.QRImprovmentTasks = new HashSet<QRImprovmentTask>();
            this.RiskAnalysisOfficeLogImprovements = new HashSet<RiskAnalysisOfficeLogImprovement>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int OfficeId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
        public Nullable<int> QRActionPlanId { get; set; }
        public Nullable<int> GoalInMoneyPercent { get; set; }
        public Nullable<int> GoalInNrPercent { get; set; }
        public Nullable<System.DateTime> ComparePeriodStart { get; set; }
        public Nullable<System.DateTime> CompanrePeriodEnd { get; set; }
        public string Name { get; set; }
        public Nullable<bool> StatisticsFinished { get; set; }
        public string Purpose { get; set; }
        public string FinishDescription { get; set; }
        public Nullable<int> FollowUpId { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<int> StartNr { get; set; }
        public Nullable<int> EndNr { get; set; }
        public Nullable<bool> Increase { get; set; }
        public Nullable<int> GoalYear { get; set; }
        public Nullable<int> GoalNr { get; set; }
        public Nullable<decimal> GoalValue { get; set; }
        public Nullable<bool> IsSimpleImprovment { get; set; }
        public Nullable<int> ResponsibleEmployeeId { get; set; }
        public Nullable<int> FinishedById { get; set; }
        public Nullable<System.DateTime> StatisticsFinishedDate { get; set; }
        public Nullable<int> EvalutationResponsibleId { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public string EvaluationDescription { get; set; }
        public Nullable<bool> IsOwnGoal { get; set; }
        public Nullable<decimal> StartValue { get; set; }
        public string StartValueUnit { get; set; }
        public string GoalValueUnit { get; set; }
        public Nullable<decimal> FinishValue { get; set; }
        public string FinishValueUnit { get; set; }
        public Nullable<bool> IsNoGoal { get; set; }
        public Nullable<int> Nr { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual FollowUp FollowUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManualPartDocumentLogImprovement> ManualPartDocumentLogImprovements { get; set; }
        public virtual Office Office { get; set; }
        public virtual QRActionPlan QRActionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovementCRHeader> QRImprovementCRHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovmentDocument> QRImprovmentDocuments { get; set; }
        public virtual QRImprovmentResponsible QRImprovmentResponsible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRImprovmentTask> QRImprovmentTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOfficeLogImprovement> RiskAnalysisOfficeLogImprovements { get; set; }
    }
}
