//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRModuleEmailNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QRModuleEmailNotification()
        {
            this.QRModuleEmailNotificationReceivers = new HashSet<QRModuleEmailNotificationReceiver>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int QRModuleId { get; set; }
        public int Weeks { get; set; }
        public int Days { get; set; }
        public int Hours { get; set; }
    
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRModuleEmailNotificationReceiver> QRModuleEmailNotificationReceivers { get; set; }
        public virtual QRModule QRModule { get; set; }
    }
}
