//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QualityReport()
        {
            this.CQReportTaskRows = new HashSet<CQReportTaskRow>();
            this.InternalControlOfficeLogRows = new HashSet<InternalControlOfficeLogRow>();
            this.PropertyControlLogs = new HashSet<PropertyControlLog>();
            this.PropertyInspectionLogs = new HashSet<PropertyInspectionLog>();
            this.PropertyMaintenanceLogs = new HashSet<PropertyMaintenanceLog>();
            this.QRAttachedFiles = new HashSet<QRAttachedFile>();
            this.QRCausedBies = new HashSet<QRCausedBy>();
            this.QRLogs = new HashSet<QRLog>();
            this.QRReportMeasures = new HashSet<QRReportMeasure>();
            this.SwedDocumentReviews = new HashSet<SwedDocumentReview>();
            this.SwedERSamplingCars = new HashSet<SwedERSamplingCar>();
            this.ToolCalibration20MeterDistance = new HashSet<ToolCalibration20MeterDistance>();
            this.ToolCalibrationACWaecoes = new HashSet<ToolCalibrationACWaeco>();
            this.ToolCalibrationBreaktesterOptimoes = new HashSet<ToolCalibrationBreaktesterOptimo>();
            this.ToolCalibrationCircumferences = new HashSet<ToolCalibrationCircumference>();
            this.ToolCalibrationFourGasMeterHexanProes = new HashSet<ToolCalibrationFourGasMeterHexanPro>();
            this.ToolCalibrationFourGasMeterPropanProes = new HashSet<ToolCalibrationFourGasMeterPropanPro>();
            this.ToolCalibrationLeakFinders = new HashSet<ToolCalibrationLeakFinder>();
            this.ToolCalibrationLightControlProes = new HashSet<ToolCalibrationLightControlPro>();
            this.ToolCalibrationLogs = new HashSet<ToolCalibrationLog>();
            this.ToolCalibrationPressureTesters = new HashSet<ToolCalibrationPressureTester>();
        }
    
        public int Id { get; set; }
        public Nullable<int> QRHeaderId { get; set; }
        public string Description { get; set; }
        public int ReportNr { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string Status { get; set; }
        public int QRResponsibleId { get; set; }
        public Nullable<int> OfficeDepartmentId { get; set; }
        public int Year { get; set; }
        public Nullable<int> QRAnalysisHeaderId { get; set; }
        public string AnalysisText { get; set; }
        public int OfficeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string FinalDecisionText { get; set; }
        public Nullable<int> QRFinalDecisionHeaderId { get; set; }
        public Nullable<decimal> FinalDecisionCost { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> AnalysisCausedById { get; set; }
        public Nullable<int> CustomerReportId { get; set; }
        public string VWToolNr { get; set; }
        public string VWOrderNr { get; set; }
        public Nullable<bool> IsRepeatRepair { get; set; }
        public string RegNr { get; set; }
        public string AoNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQReportTaskRow> CQReportTaskRows { get; set; }
        public virtual CustomerReport CustomerReport { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLogRow> InternalControlOfficeLogRows { get; set; }
        public virtual OfficeDepartment OfficeDepartment { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyControlLog> PropertyControlLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyInspectionLog> PropertyInspectionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyMaintenanceLog> PropertyMaintenanceLogs { get; set; }
        public virtual QRAnalysisHeader QRAnalysisHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRAttachedFile> QRAttachedFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCausedBy> QRCausedBies { get; set; }
        public virtual QRFinalDecisionHeader QRFinalDecisionHeader { get; set; }
        public virtual QRHeader QRHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRLog> QRLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRReportMeasure> QRReportMeasures { get; set; }
        public virtual QRResponsible QRResponsible { get; set; }
        public virtual QRStatu QRStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedDocumentReview> SwedDocumentReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedERSamplingCar> SwedERSamplingCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibration20MeterDistance> ToolCalibration20MeterDistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationACWaeco> ToolCalibrationACWaecoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationBreaktesterOptimo> ToolCalibrationBreaktesterOptimoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationCircumference> ToolCalibrationCircumferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationFourGasMeterHexanPro> ToolCalibrationFourGasMeterHexanProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationFourGasMeterPropanPro> ToolCalibrationFourGasMeterPropanProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLeakFinder> ToolCalibrationLeakFinders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLightControlPro> ToolCalibrationLightControlProes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationPressureTester> ToolCalibrationPressureTesters { get; set; }
    }
}
