//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAnalysisSubGroupRow
    {
        public int Id { get; set; }
        public int RiskAnalysisCompanyRowId { get; set; }
        public int RiskAnalysisSubGroupId { get; set; }
    
        public virtual RiskAnalysisCompanyRow RiskAnalysisCompanyRow { get; set; }
        public virtual RiskAnalysisSubGroup RiskAnalysisSubGroup { get; set; }
    }
}
