//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAnalysisOfficeLogImprovement
    {
        public int Id { get; set; }
        public int QRImprovmentId { get; set; }
        public int RiskAnalysisOfficeLogId { get; set; }
    
        public virtual QRImprovment QRImprovment { get; set; }
        public virtual RiskAnalysisOfficeLog RiskAnalysisOfficeLog { get; set; }
    }
}
