//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAnalysisOfficeLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskAnalysisOfficeLog()
        {
            this.RiskAnalysisOfficeLogImprovements = new HashSet<RiskAnalysisOfficeLogImprovement>();
            this.RiskAnalysisOfficeLogRows = new HashSet<RiskAnalysisOfficeLogRow>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public int RiskAnalysisOfficeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RiskAnalysisOffice RiskAnalysisOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOfficeLogImprovement> RiskAnalysisOfficeLogImprovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOfficeLogRow> RiskAnalysisOfficeLogRows { get; set; }
    }
}
