//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAnalysisCompanyRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskAnalysisCompanyRow()
        {
            this.RiskAnalysisOfficeLogRows = new HashSet<RiskAnalysisOfficeLogRow>();
            this.RiskAnalysisSubGroupRows = new HashSet<RiskAnalysisSubGroupRow>();
        }
    
        public int Id { get; set; }
        public int RiskAnalysisCompanyId { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
    
        public virtual RiskAnalysisCompany RiskAnalysisCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOfficeLogRow> RiskAnalysisOfficeLogRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisSubGroupRow> RiskAnalysisSubGroupRows { get; set; }
    }
}
