//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAnalysisCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskAnalysisCompany()
        {
            this.RiskAnalysisCompanyRows = new HashSet<RiskAnalysisCompanyRow>();
            this.RiskAnalysisOffices = new HashSet<RiskAnalysisOffice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Deleted { get; set; }
        public int CompanyId { get; set; }
        public int RiskAnalysisGroupId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual RiskAnalysisGroup RiskAnalysisGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisCompanyRow> RiskAnalysisCompanyRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAnalysisOffice> RiskAnalysisOffices { get; set; }
    }
}
