//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedManagementReview381
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SwedManagementReview381()
        {
            this.SwedManagementReview381Employees = new HashSet<SwedManagementReview381Employees>();
        }
    
        public int Id { get; set; }
        public string InformationComment { get; set; }
        public string LastReview { get; set; }
        public string InternalReview { get; set; }
        public string ImprovmentSuggestion { get; set; }
        public string ExternalReviewSwedac { get; set; }
        public string SamplingResult { get; set; }
        public string SaftyRutinesDFS { get; set; }
        public string RiskAnalysisPrevention { get; set; }
        public string CompetenceEmployees { get; set; }
        public string CustomerComplaint { get; set; }
        public string PolicyChange { get; set; }
        public string RiskAnalysisActuality { get; set; }
        public string ChangesManagementSystem { get; set; }
        public string EmployeeQuestions { get; set; }
        public string EquipmentPremisisNeeds { get; set; }
        public string OtherImprortantInfo { get; set; }
        public string ImprovmentEfficiencySystem { get; set; }
        public string ImprovmentFulfillStandarnds { get; set; }
        public string MoreResources { get; set; }
        public string FollowUpGoals { get; set; }
        public string NewGoals { get; set; }
        public string AchiveGoals { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public string Name { get; set; }
        public int OfficeId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedManagementReview381Employees> SwedManagementReview381Employees { get; set; }
    }
}
