//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedManagementReview381Employees
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int SwedManageMentReview381Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SwedManagementReview381 SwedManagementReview381 { get; set; }
    }
}
