//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedAssessmentSkillsER
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int PerformedOnId { get; set; }
        public int CreatedBy { get; set; }
        public bool CorrectSystemKnowledge { get; set; }
        public bool CorrectNotes { get; set; }
        public bool CorrectTypes { get; set; }
        public bool CorrectIdentity { get; set; }
        public bool CorrectPhysical { get; set; }
        public bool CorrectRelivant { get; set; }
        public bool CorrectLightControl { get; set; }
        public bool CorrectLimits { get; set; }
        public bool CorrectMethods { get; set; }
        public bool CorrectRegulation { get; set; }
        public bool CorrectDocumentation { get; set; }
        public bool CorrectDifference { get; set; }
        public bool CorrectCBR { get; set; }
        public bool CorrectArchiving { get; set; }
        public bool CorrectProcessing { get; set; }
        public string AssessementNotes { get; set; }
        public bool KnowledgeRulesOk { get; set; }
        public bool ConsistentOk { get; set; }
        public bool DecisionsOk { get; set; }
        public bool DocumentationOk { get; set; }
        public bool ControllerOk { get; set; }
        public bool Deleted { get; set; }
        public string Name { get; set; }
        public int OfficeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Office Office { get; set; }
    }
}
