//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedJointInfoEducation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SwedJointInfoEducation()
        {
            this.SwedJointInfoEducationParticipants = new HashSet<SwedJointInfoEducationParticipant>();
        }
    
        public int Id { get; set; }
        public string InfoEducationDescription { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public int OfficeId { get; set; }
        public string Name { get; set; }
        public int EducatorId { get; set; }
        public System.DateTime EducationDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedJointInfoEducationParticipant> SwedJointInfoEducationParticipants { get; set; }
    }
}
