//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedAssessmentSkillsTA
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int PerformedOnId { get; set; }
        public int CreatedBy { get; set; }
        public bool CorrectStandardKnowlege { get; set; }
        public bool CorrectRegulationKnowlege { get; set; }
        public bool CorrectSystemKnowlege { get; set; }
        public bool CorrectDemandsKnowlege { get; set; }
        public bool CorrectAccreditationKnowlege { get; set; }
        public bool CorrectCalibrationKnowlege { get; set; }
        public bool CorrectMethodsKnowlege { get; set; }
        public bool CorrectControlKnowledge { get; set; }
        public bool CorrectIndependentKnowlege { get; set; }
        public string AssessementNotes { get; set; }
        public bool Deleted { get; set; }
        public string Name { get; set; }
        public int OfficeId { get; set; }
        public bool ControllerOk { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Office Office { get; set; }
    }
}
