//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedOfficeArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SwedOfficeArea()
        {
            this.SwedOfficeAreaEmployees = new HashSet<SwedOfficeAreaEmployee>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int SwedAreaId { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual SwedArea SwedArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwedOfficeAreaEmployee> SwedOfficeAreaEmployees { get; set; }
    }
}
