//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedOfficeAreaEmployee
    {
        public int Id { get; set; }
        public int SwedOfficeAreaId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
        public string Issuer { get; set; }
        public int SwedAreaRoleId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SwedAreaRole SwedAreaRole { get; set; }
        public virtual SwedOfficeArea SwedOfficeArea { get; set; }
    }
}
