//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwedERSamplingCar
    {
        public int Id { get; set; }
        public string ReportNr { get; set; }
        public string RegNr { get; set; }
        public bool CorrectVehicle { get; set; }
        public bool CorrectRepair { get; set; }
        public bool CorrectReport { get; set; }
        public bool CopyOfProtocol { get; set; }
        public bool DirectRegistration { get; set; }
        public bool CorrectWorkorder { get; set; }
        public Nullable<bool> BreakTestPrint { get; set; }
        public Nullable<bool> EmmisionPrint { get; set; }
        public Nullable<bool> SupplierCopy { get; set; }
        public bool Impartiality { get; set; }
        public int OfficeId { get; set; }
        public int CreatedById { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> QualityReportId { get; set; }
        public string Name { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        public virtual QualityReport QualityReport { get; set; }
    }
}
