//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolReplacing
    {
        public int Id { get; set; }
        public string VAGToolNr { get; set; }
        public string VAGOrderNr { get; set; }
        public int ToolId { get; set; }
        public string Description { get; set; }
    
        public virtual Tool Tool { get; set; }
    }
}
