//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolMaintenanceLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolMaintenanceLog()
        {
            this.ToolLogs = new HashSet<ToolLog>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public string MaintenanceDoc { get; set; }
        public string MaintenanceText { get; set; }
        public bool Deleted { get; set; }
        public Nullable<bool> RutineDone { get; set; }
        public string RutineNotDoneReason { get; set; }
        public string RutineName { get; set; }
        public Nullable<bool> UseWebForm { get; set; }
        public Nullable<int> ToolMaintenanceTypeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolLog> ToolLogs { get; set; }
        public virtual ToolMaintenanceType ToolMaintenanceType { get; set; }
    }
}
