//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolLog
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public string Description { get; set; }
        public int LogTypeId { get; set; }
        public Nullable<int> CalibrationLogId { get; set; }
        public Nullable<int> MaintenanceLogId { get; set; }
        public int ToolId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> OfficeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        public virtual Tool Tool { get; set; }
        public virtual ToolCalibrationLog ToolCalibrationLog { get; set; }
        public virtual ToolLogType ToolLogType { get; set; }
        public virtual ToolMaintenanceLog ToolMaintenanceLog { get; set; }
    }
}
