//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCalibrationCircumference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolCalibrationCircumference()
        {
            this.ToolCalibrationLogs = new HashSet<ToolCalibrationLog>();
        }
    
        public int Id { get; set; }
        public int Circumference { get; set; }
        public Nullable<int> CircumferenceAftAdj { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> QualityReportId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual QualityReport QualityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs { get; set; }
    }
}
