//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolGroupInventoryLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolGroupInventoryLog()
        {
            this.ToolGroupInventories = new HashSet<ToolGroupInventory>();
            this.ToolGroupInventoryLogRows = new HashSet<ToolGroupInventoryLogRow>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ToolGroupInventoryId { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
        public System.DateTime InventoryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolGroupInventory> ToolGroupInventories { get; set; }
        public virtual ToolGroupInventory ToolGroupInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolGroupInventoryLogRow> ToolGroupInventoryLogRows { get; set; }
    }
}
