//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolBorrowed
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DepartmentPlaceId { get; set; }
        public int EmployeeId { get; set; }
        public int OfficeId { get; set; }
        public int ToolId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        public virtual Tool Tool { get; set; }
        public virtual ToolDepartment ToolDepartment { get; set; }
        public virtual ToolDepartmentPlace ToolDepartmentPlace { get; set; }
    }
}
