//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolMaintenanceRutine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolMaintenanceRutine()
        {
            this.Tools = new HashSet<Tool>();
            this.ToolMaintenanceRutineOffices = new HashSet<ToolMaintenanceRutineOffice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Rutine { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolMaintenanceRutineOffice> ToolMaintenanceRutineOffices { get; set; }
    }
}
