//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCalibrationACWaeco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolCalibrationACWaeco()
        {
            this.ToolCalibrationLogs = new HashSet<ToolCalibrationLog>();
        }
    
        public int Id { get; set; }
        public bool DamgeControl { get; set; }
        public bool ScaleZeroCheck { get; set; }
        public double LowPressureZero { get; set; }
        public double LowPressureTwo { get; set; }
        public double LowPressureFour { get; set; }
        public double LowPressureSix { get; set; }
        public double LowPressureEight { get; set; }
        public double LowPressureFifteen { get; set; }
        public double HighPressureZero { get; set; }
        public double HighPressureTwo { get; set; }
        public double HighPressureFour { get; set; }
        public double HighPressureSix { get; set; }
        public double HighPressureEight { get; set; }
        public double HighPressureFifteen { get; set; }
        public double HighPressureSixteen { get; set; }
        public double HighPressureTwentyTwo { get; set; }
        public double HighPressureTwentyEight { get; set; }
        public double HighPressureThirty { get; set; }
        public double PressureAndDenceZero { get; set; }
        public double PressureAndDenceTwo { get; set; }
        public double PressureAndDenceFour { get; set; }
        public double PressureAndDenceSix { get; set; }
        public double PressureAndDenceEight { get; set; }
        public double PressureAndDenceFifteen { get; set; }
        public double PressureAndDenceSixteen { get; set; }
        public double PressureAndDenceTwentyTwo { get; set; }
        public double PressureAndDenceTwentyEight { get; set; }
        public double PressureAndDenceThirty { get; set; }
        public bool LeakFinderControl { get; set; }
        public bool VaccumPumpControl { get; set; }
        public bool VaccumMeterControl { get; set; }
        public Nullable<double> UnderPressureDigital { get; set; }
        public Nullable<double> UnderPressureAnalog { get; set; }
        public Nullable<double> UnderPressureK { get; set; }
        public Nullable<double> UnderPressureRefVacc { get; set; }
        public Nullable<double> UnderPressureDifference { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> QualityReportId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual QualityReport QualityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs { get; set; }
    }
}
