//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCalibrationFourGasMeterHexanPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolCalibrationFourGasMeterHexanPro()
        {
            this.ToolCalibrationLogs = new HashSet<ToolCalibrationLog>();
        }
    
        public int Id { get; set; }
        public decimal GasCO { get; set; }
        public decimal GasCORef { get; set; }
        public Nullable<decimal> GasCOAfterAdj { get; set; }
        public decimal GasHC { get; set; }
        public decimal GasHCRef { get; set; }
        public Nullable<decimal> GasHCAfterAdj { get; set; }
        public decimal GasCO2 { get; set; }
        public decimal GasCO2Ref { get; set; }
        public Nullable<decimal> GasCO2AfterAdj { get; set; }
        public decimal GasO2 { get; set; }
        public decimal GasO2Ref { get; set; }
        public Nullable<decimal> GasO2AfterAdj { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> QualityReportId { get; set; }
        public string GasBottleNr { get; set; }
        public string PefFactor { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual QualityReport QualityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs { get; set; }
    }
}
