//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCalibrationDocument
    {
        public int Id { get; set; }
        public int ToolId { get; set; }
        public int ToolDocumentId { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual ToolDocument ToolDocument { get; set; }
    }
}
