//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolGroupInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolGroupInventory()
        {
            this.ToolGroupInventoryLogs = new HashSet<ToolGroupInventoryLog>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public bool IsAll { get; set; }
        public int IntervallNr { get; set; }
        public string IntervallUnit { get; set; }
        public System.DateTime Next { get; set; }
        public int ResponsibleId { get; set; }
        public int ReminderNr { get; set; }
        public string ReminderUnit { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public Nullable<int> OnGoingLogId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
        public virtual ToolGroup ToolGroup { get; set; }
        public virtual ToolGroupInventoryLog ToolGroupInventoryLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolGroupInventoryLog> ToolGroupInventoryLogs { get; set; }
    }
}
