//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolSettingsOffice
    {
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public Nullable<bool> UseIndeco { get; set; }
        public string IndecoPassword { get; set; }
        public Nullable<int> IndecoToolGroupId { get; set; }
        public Nullable<bool> VarningAsStart { get; set; }
        public Nullable<bool> VAGPlikt { get; set; }
        public Nullable<bool> ImportTools { get; set; }
        public Nullable<int> MaintenanceReminderNr { get; set; }
        public string MaintenanceReminderUnit { get; set; }
        public Nullable<int> CalibrationReminderNr { get; set; }
        public string CalibrationReminderUnit { get; set; }
        public Nullable<bool> UseWebBrowser { get; set; }
        public Nullable<bool> HasCalibrationMethods { get; set; }
        public Nullable<bool> HasProductPrice { get; set; }
        public Nullable<bool> HasToolCostOffice { get; set; }
        public Nullable<int> ConnectedOfficeId { get; set; }
        public string ToolsFile { get; set; }
        public string SpecialToolFile { get; set; }
        public Nullable<System.DateTime> ToolsFileDate { get; set; }
        public Nullable<System.DateTime> SpecialToolsFileDate { get; set; }
        public Nullable<bool> HideToolPickButton { get; set; }
        public Nullable<bool> ProductReadOnly { get; set; }
        public Nullable<bool> ManufacturerReadOnly { get; set; }
        public Nullable<bool> ModelReadOnly { get; set; }
        public Nullable<bool> DepartmentReadOnly { get; set; }
        public Nullable<bool> DepartmenPlaceReadOnly { get; set; }
        public Nullable<bool> PlaceLocationReadOnly { get; set; }
        public Nullable<bool> HideNrOfTools { get; set; }
        public string NewVAGFile { get; set; }
        public Nullable<System.DateTime> NewVAGFileDate { get; set; }
        public Nullable<bool> UseJB { get; set; }
        public Nullable<bool> UseFABdetect { get; set; }
        public Nullable<bool> UseRISE { get; set; }
        public Nullable<bool> UseSun { get; set; }
        public Nullable<bool> NewVAGPliktList { get; set; }
        public string VAGSkodaFile { get; set; }
        public string VAGVWFile { get; set; }
        public string VAGVWTrpFile { get; set; }
        public string VAGSeatFile { get; set; }
        public string VAGAudiFile { get; set; }
        public Nullable<System.DateTime> VAGSkodaFileDate { get; set; }
        public Nullable<System.DateTime> VAGVWFileDate { get; set; }
        public Nullable<System.DateTime> VAGVWTrpFileDate { get; set; }
        public Nullable<System.DateTime> VAGSeatFileDate { get; set; }
        public Nullable<System.DateTime> VAGAudiFileDate { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual Office Office1 { get; set; }
        public virtual ToolGroup ToolGroup { get; set; }
    }
}
