//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCalibrationPressureTester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolCalibrationPressureTester()
        {
            this.ToolCalibrationLogs = new HashSet<ToolCalibrationLog>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> PZero { get; set; }
        public Nullable<decimal> PZeroRef { get; set; }
        public Nullable<decimal> PFive { get; set; }
        public Nullable<decimal> PFiveRef { get; set; }
        public Nullable<decimal> PTen { get; set; }
        public Nullable<decimal> PTenRef { get; set; }
        public Nullable<decimal> PTwenty { get; set; }
        public Nullable<decimal> PTwentyRef { get; set; }
        public Nullable<decimal> PThirty { get; set; }
        public Nullable<decimal> PThirtyRef { get; set; }
        public Nullable<decimal> PForty { get; set; }
        public Nullable<decimal> PFortyRef { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> QualityReportId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual QualityReport QualityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCalibrationLog> ToolCalibrationLogs { get; set; }
    }
}
