//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolVWPricesCompany
    {
        public int Id { get; set; }
        public string ToolOrderNr { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> Price { get; set; }
        public string ToolNr { get; set; }
        public string Name { get; set; }
        public string TimeUnit { get; set; }
        public Nullable<int> TimeNr { get; set; }
        public string CalibrationType { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
