//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolProductPriceOffice
    {
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int ToolProductId { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public string CustomerDemands { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual ToolProduct ToolProduct { get; set; }
    }
}
