//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCalibrationLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolCalibrationLog()
        {
            this.ToolLogs = new HashSet<ToolLog>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public string CalibrationDoc { get; set; }
        public string CalibrationResult { get; set; }
        public string CalibrationText { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> ToolCalibrationLightControlProId { get; set; }
        public Nullable<int> QualityReportId { get; set; }
        public Nullable<int> ToolCalibrationFourGasMeterPropanProId { get; set; }
        public Nullable<int> ToolCalibrationFourGasMeterHexanProId { get; set; }
        public Nullable<int> ToolCalibrationBreaktesterOptimoId { get; set; }
        public Nullable<int> ToolCalibration20MeterDistanceId { get; set; }
        public Nullable<int> ToolCalibrationCircumferenceId { get; set; }
        public Nullable<int> ToolCalibrationACWaecoId { get; set; }
        public Nullable<bool> UseWebForm { get; set; }
        public Nullable<int> ToolCalibrationPressureTesterId { get; set; }
        public Nullable<int> ToolCalibrationLeakFinderId { get; set; }
        public Nullable<int> ToolCalibrationDocumentReportId { get; set; }
        public Nullable<int> ReportNr { get; set; }
        public string RegNo { get; set; }
        public string Signature { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovementDescription { get; set; }
        public Nullable<bool> UseSignatur { get; set; }
        public Nullable<int> ToolCalibrationTypeId { get; set; }
        public Nullable<bool> AdjustmentDone { get; set; }
        public Nullable<System.DateTime> AdjustmentApprovalDate { get; set; }
        public Nullable<int> AdjustmentApprovalById { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual QualityReport QualityReport { get; set; }
        public virtual ToolCalibration20MeterDistance ToolCalibration20MeterDistance { get; set; }
        public virtual ToolCalibrationACWaeco ToolCalibrationACWaeco { get; set; }
        public virtual ToolCalibrationBreaktesterOptimo ToolCalibrationBreaktesterOptimo { get; set; }
        public virtual ToolCalibrationCircumference ToolCalibrationCircumference { get; set; }
        public virtual ToolCalibrationDocumentReport ToolCalibrationDocumentReport { get; set; }
        public virtual ToolCalibrationFourGasMeterHexanPro ToolCalibrationFourGasMeterHexanPro { get; set; }
        public virtual ToolCalibrationFourGasMeterPropanPro ToolCalibrationFourGasMeterPropanPro { get; set; }
        public virtual ToolCalibrationLeakFinder ToolCalibrationLeakFinder { get; set; }
        public virtual ToolCalibrationLightControlPro ToolCalibrationLightControlPro { get; set; }
        public virtual ToolCalibrationPressureTester ToolCalibrationPressureTester { get; set; }
        public virtual ToolCalibrationType ToolCalibrationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolLog> ToolLogs { get; set; }
    }
}
