//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleBrand()
        {
            this.CompanyVehicleBrands = new HashSet<CompanyVehicleBrand>();
            this.InternalControlOfficeLogs = new HashSet<InternalControlOfficeLog>();
            this.InternalControlOfficeVehicleBrandGoals = new HashSet<InternalControlOfficeVehicleBrandGoal>();
            this.OfficeVehicleBrandResponsibles = new HashSet<OfficeVehicleBrandResponsible>();
            this.VehicleCompanies = new HashSet<VehicleCompany>();
        }
    
        public int Id { get; set; }
        public string VehicleBrandCode { get; set; }
        public string VehicleBrandName { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyVehicleBrand> CompanyVehicleBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeLog> InternalControlOfficeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalControlOfficeVehicleBrandGoal> InternalControlOfficeVehicleBrandGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeVehicleBrandResponsible> OfficeVehicleBrandResponsibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleCompany> VehicleCompanies { get; set; }
    }
}
