//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisoftMobileWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleCompany()
        {
            this.ACReports = new HashSet<ACReport>();
            this.CarPreSales = new HashSet<CarPreSale>();
            this.CustomerReportPositives = new HashSet<CustomerReportPositive>();
            this.CustomerReports = new HashSet<CustomerReport>();
        }
    
        public string RegNr { get; set; }
        public int CompanyId { get; set; }
        public int OwnerId { get; set; }
        public string Manufacture { get; set; }
        public string Model { get; set; }
        public string Chassinr { get; set; }
        public string Type { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Color { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Milage { get; set; }
        public int Id { get; set; }
        public Nullable<int> VehicleBrandId { get; set; }
        public Nullable<bool> HasWinterTires { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACReport> ACReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPreSale> CarPreSales { get; set; }
        public virtual Company Company { get; set; }
        public virtual CustomerCompany CustomerCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReportPositive> CustomerReportPositives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReport> CustomerReports { get; set; }
        public virtual VehicleBrand VehicleBrand { get; set; }
    }
}
